USE SISTEMA_PEDIDOS

--CONSTRAINT(REGRA) - CHECK 
EXEC SP_HELP TB_CARGO

--CHECK PARA A COLUNA SALARIO_INIC (COLUNA NAO PODE SER NEGATIVA)
/*
SINTAXE PARA A CONSTRAINT CHECK
ALTER TABLE <NOME_TABELA>
ADD
CONSTRAINT <NOME_INTERNO_REGRA> CHECK(NOME_COLUNA<CONDIÇÃO>)
*/
ALTER TABLE TB_CARGO
ADD
CONSTRAINT CK_CARGO_SALARIOINIC CHECK (SALARIO_INIC>0)

EXEC SP_HELP TB_CARGO

--CONSTRAINT UNIQUE
--COLUNA CPF NAO PODE REPETIR
EXEC SP_HELP TB_EMPREGADO

/*
SINTAXE DA CONSTRAINT UNIQUE
ALTER TABLE <NOME_TABELA>
ADD
CONSTRAINT <NOME_INTERNO_REGRA> UNIQUE(NOME_COLUNA)
*/
ALTER TABLE TB_EMPREGADO
ADD
CONSTRAINT UQ_EMPREGADO_CPF UNIQUE(CPF)

EXEC SP_HELP TB_EMPREGADO

