-- COLOCAR EM USO O BANCO DE DADOS SISTEMA_PEDIDOS
USE SISTEMA_PEDIDOS

--VISUALIZAR A ESTRUTURA DA TABELA TB_EMPREGADO
EXEC SP_HELP TB_EMPREGADO

--APAGAR A COLUNA CPF
/*
SINTAXE PARA APAGAR UMA COLUNA
ALTER TABLE <NOME_TABELA> 
DROP COLUMN <NOME_COLUNA>
*/
ALTER TABLE TB_EMPREGADO
DROP COLUMN CPF

--ACRESCENTAR A COLUNA CPF NOVAMENTE COM O TIPO DE DADOS INT
ALTER TABLE TB_EMPREGADO
ADD
CPF INT NOT NULL

--ALTERAR O TIPO DE DADOS DA COLUNA CPF DE INT PARA BIGINT
/*
SINTAXE PARA ALTERAR O TIPO DE DADOS DE UMA COLUNA
ALTER TABLE <NOME_TABELA>
ALTER COLUMN <NOME_COLUNA><TIPO_DE_DADOS>
*/
ALTER TABLE TB_EMPREGADO
ALTER COLUMN CPF BIGINT NOT NULL