USE PEDIDOS 

--FUNÇOES DE TEXTO
--FUNÇAO REPLICATE - REPLICA UMA SEQUENCIA DE CARACTERES
SELECT REPLICATE(' *-* ',25) AS FORMA

--FUNÇÃO REVERSE
--LE UM TEXTO DA ESQUERDA PARA A DIREITA
SELECT REVERSE('AMOR') AS PALAVRA

--CONCATENAÇÃO
--FAZER UMA QUERY PARA RETORNAR O NOME DO FUNCIONARIO SEGUIDO DO SALARIO
--NOME:SALARIO
--EXEMPLO: OLAVO:1200
SELECT NOME	+ ': ' + CAST(SALARIO AS CHAR(10)) AS NOME
FROM TB_EMPREGADO

--CONCATENAÇÃO COM DATA
SELECT NOME	+ ': ' + CAST(DATA_NASCIMENTO AS CHAR (10))
FROM TB_EMPREGADO

--NOME: DD/MM/AAAA
--OLAVO TRINDADE: 06/06/1950
--FUNÇAO CONVERT
SELECT NOME + ': ' + CONVERT(CHAR(10),DATA_NASCIMENTO,103) AS NOME
FROM TB_EMPREGADO

SELECT NOME + ': ' + CONVERT(CHAR(10),DATA_NASCIMENTO,3) AS NOME
FROM TB_EMPREGADO

SELECT NOME + ': ' + CONVERT(CHAR(10),DATA_NASCIMENTO,121) AS NOME
FROM TB_EMPREGADO
