USE PEDIDOS

--CLAUSULA WHERE
/*
OPERADORES RELACIONAIS
= IGUAL
<> OU != DIFERENTE
> MAIOR QUE
< MENOR QUE
>= MAIOR OU IGUAL
<= MENOR IGUAL
*/

-- FAZER UMA QUERY PARA RETORNAR O COD_DEPTO, NOME, SALARIO
--COM O FILTRO DA COLUNA SALARIO=500
SELECT COD_DEPTO, NOME, SALARIO
FROM TB_EMPREGADO 
WHERE SALARIO = 500

--FAZER UMA QUERY PARA RETORNAR OS FUNCIONARIOS QUE POSSUEM SALARIO DIFERENTE DE 500
SELECT COD_DEPTO, NOME, SALARIO
FROM TB_EMPREGADO 
WHERE SALARIO != 500
ORDER BY SALARIO

--FAZER UMA QUERY PARA RETORNAR OS FUNCIONARIOS QUE GANHAM MAIS QUE 1200
SELECT COD_DEPTO, NOME, SALARIO
FROM TB_EMPREGADO 
WHERE SALARIO > 1200
ORDER BY SALARIO

--FAZER UMA QUERY PARA RETORNAR OS FUNCIONARIOS QUE IGUAL OU MAIS QUE 1200
SELECT COD_DEPTO, NOME, SALARIO
FROM TB_EMPREGADO 
WHERE SALARIO >= 1200
ORDER BY SALARIO

--FAZER UMA QUERY PARA RETORNAR OS FUNCIONARIOS QUE GANHAM MENOS QUE 1200
SELECT COD_DEPTO, NOME, SALARIO
FROM TB_EMPREGADO 
WHERE SALARIO < 1200
ORDER BY SALARIO DESC

