USE SISTEMA_PEDIDOS

SELECT * 
FROM TB_EMPREGADO

--CRIAR INDICE PARA A COLUNA CPF COM O NOME NDX_CPF NA TABELA TB_EMPREGADO
CREATE NONCLUSTERED INDEX NDX_CPF 
ON TB_EMPREGADO (CPF)

--VISUALIZAR O INDICE CRIADO
EXEC SP_HELP TB_EMPREGADO

SELECT *
FROM TB_EMPREGADO
WHERE CPF=14513348934

--CRIAR INDICE EM UMA VISAO
CREATE VIEW VW_EMPREGADO
WITH SCHEMABINDING
AS
SELECT CODFUN
		,NOME
		,DATA_ADMISSAO
		,COD_CARGO
		,SALARIO
FROM DBO.TB_EMPREGADO

SELECT *
FROM VW_EMPREGADO

EXEC SP_HELP VW_EMPREGADO

--CRIAR UM INDICE PARA A COLUNA CODFUN NA VISAO VW_EMPREGADO
CREATE UNIQUE CLUSTERED INDEX NDX_CODFUN
ON VW_EMPREGADO(CODFUN)

SELECT *
FROM VW_EMPREGADO
WHERE CODFUN=3

--APAGAR UM INDICE
DROP INDEX NDX_CODFUN ON VW_EMPREGADO
