--COLOCAR EM USO O BANCO DE DADOS SISTEMA_PEDIDOS
USE SISTEMA_PEDIDOS
--TABELAS EXISTENTES NO BANCO EM USO
SELECT * 
FROM SYS.TABLES

--CRIAR A TABELA TB_CARGO
CREATE TABLE TB_CARGO
(
COD_CARGO INT NOT NULL
,CARGO VARCHAR(30) NOT NULL
,SALARIO_INIC FLOAT NOT NULL
,CONSTRAINT PK_CODCARGO PRIMARY KEY(COD_CARGO)
)

--VISUALIZAR A ESTRUTURA DA TABELA
EXEC SP_HELP TB_CARGO
EXEC SP_HELP TB_DEPARTAMENTO

--CRIAR A TABELA TB_EMPREGADO
--CONSTRAINT DE CHAVE PRIMARIA PARA A COLUNA CODFUN
--CONSTRAINT DE COD_DEPTO E COD_CARGO
CREATE TABLE TB_EMPREGADO
(CODFUN INT NOT NULL
,NOME VARCHAR(35) NOT NULL
,NUM_DEPEND SMALLINT NOT NULL
,DATA_NASCIMENTO DATETIME NOT NULL
,COD_DEPTO INT NOT NULL
,COD_CARGO INT NOT NULL
,DATA_ADMISSAO DATETIME NOT NULL
,SALARIO NUMERIC(18,2) NOT NULL
,PREMIO_MENSAL NUMERIC(10,2) NOT NULL
,SINDICALIZADO CHAR(1) NOT NULL
,OBS TEXT NOT NULL
,FOTO IMAGE NOT NULL
,CONSTRAINT PK_CODFUN PRIMARY KEY(CODFUN)
)

--SINTAXE DA CHAVE ESTRANGEIRA
/*
CONSTRAINT <NOME_FK> FOREINGN KEY(CAMPO)
REFERENCES <NOME_TABELA> (CAMPO-CHAVE PRIMARIA)
*/
--COD_DEPTO
--COD_CARGO
ALTER TABLE TB_EMPREGADO
ADD
CONSTRAINT FK_CODDEPTO FOREIGN KEY(COD_DEPTO)
REFERENCES TB_DEPARTAMENTO(COD_DEPTO)

ALTER TABLE TB_EMPREGADO
ADD
CONSTRAINT FK_CODARGO FOREIGN KEY(COD_CARGO)
REFERENCES TB_CARGO(COD_CARGO)

--VISUALIZAR A ESTRUTURA DA TABELA EMPREGADO
EXEC SP_HELP TB_EMPREGADO