USE PEDIDOS

--ARMAZENAR DADOS EM MEMORIA
--CTE - COMMOM TABLE EXPRESSION
WITH CARGO_EMP(NOME,COD_CARGO, SALARIO)
AS
(SELECT NOME
		,COD_CARGO
		,SALARIO
FROM TB_EMPREGADO)
--CCONTAR A QUANTIDADE DE FUNCIONARIOS POR CARGO
SELECT DADOS_CTE.COD_CARGO
		,CARGO.CARGO
		,COUNT(DADOS_CTE.NOME) AS QTDE_FUNCIONARIOS
FROM CARGO_EMP AS DADOS_CTE
INNER JOIN TB_CARGO AS CARGO
ON DADOS_CTE.COD_CARGO=CARGO.COD_CARGO
GROUP BY DADOS_CTE.COD_CARGO
		,CARGO.CARGO
ORDER BY DADOS_CTE.COD_CARGO
