USE PEDIDOS

--DELETE COM TOP
--CRIAR UMA TABELA A PARTIR DO COMANDO SELECT INTO
--ESTA TABELA CONTERA OS REGISTROS DOS LIENTES DO ESTADO DE MG
--TABELA FONTE TB_CLIENTE
SELECT *
INTO CLIENTE_MG
FROM TB_CLIENTE
WHERE ESTADO = 'MG'

SELECT *
FROM CLIENTE_MG

--DELETE COM TOP
--APAGAR OS 10 PRIMEIROS REGISTROS DA TABELA CLIENTE MG
DELETE TOP(10) 
FROM CLIENTE_MG

SELECT * 
FROM CLIENTE_MG

--APAGAR OS 5 PRIMEIROS REGISTROS DA TABELA CLIENTE_MG
DELETE TOP (5)
FROM CLIENTE_MG

--DELETE COM OUTPUT
--APAGAR OS 3 PRIMEIROS REGISTROS DA TABELA CLIENTE_MG
BEGIN TRAN
DELETE TOP(3)
FROM CLIENTE_MG
OUTPUT deleted.*

SELECT * 
FROM CLIENTE_MG

ROLLBACK
