USE PEDIDOS

--DELETE COM JOIN
SELECT *
FROM TB_PEDIDO_TEMP

--DELETAR AS VENDAS DO VENDEDOR MARCELO NO PERIODO DE 
SELECT *
FROM TB_PEDIDO_TEMP
WHERE DATA_EMISSAO BETWEEN '2016/12/16' AND '2016/12/31'
AND CODVEN =2

BEGIN TRAN

DELETE 
FROM TB_PEDIDO_TEMP
FROM TB_PEDIDO_TEMP AS PED
INNER JOIN TB_VENDEDOR AS VEND
ON PED.CODVEN=VEND.CODVEN
WHERE PED.DATA_EMISSAO BETWEEN '2016/12/16' AND '2016/12/31'
AND VEND.NOME = 'MARCELO'

ROLLBACK

--OUTPUT
BEGIN TRAN

DELETE 
FROM TB_PEDIDO_TEMP
OUTPUT DELETED.*
FROM TB_PEDIDO_TEMP AS PED
INNER JOIN TB_VENDEDOR AS VEND
ON PED.CODVEN=VEND.CODVEN
WHERE PED.DATA_EMISSAO BETWEEN '2016/12/16' AND '2016/12/31'
AND VEND.NOME = 'MARCELO'

ROLLBACK