USE PEDIDOS

--DELETE COM SUBQUERY
--APAGAR OS REGISTROS DAS VENDAS DO VENDEDOR MARCELO NO PERIODO DE 2016/12/01 A 2016/12/15
--CRIAR UMA COPIA DA TABELA TB_PEDIDO
SELECT *
INTO TB_PEDIDO_TEMP
FROM TB_PEDIDO

SELECT *
FROM TB_PEDIDO_TEMP
WHERE CODVEN=2
AND DATA_EMISSAO BETWEEN '2016/12/01' AND '2016/12/15'

BEGIN TRAN

DELETE
FROM TB_PEDIDO_TEMP
WHERE DATA_EMISSAO BETWEEN '2016/12/01' AND '2016/12/15'
AND CODVEN = (SELECT CODVEN
				FROM TB_VENDEDOR
				WHERE NOME = 'MARCELO')

ROLLBACK

--COM OUTPUT
BEGIN TRAN

DELETE
FROM TB_PEDIDO_TEMP
OUTPUT deleted.*
WHERE DATA_EMISSAO BETWEEN '2016/12/01' AND '2016/12/15'
AND CODVEN = (SELECT CODVEN
				FROM TB_VENDEDOR
				WHERE NOME = 'MARCELO')
COMMIT

