USE PEDIDOS 

SELECT *
FROM EMPREGADO_TEMP

--APAGAR TODOS OS REGISTROS DA TABELA EMPREGADO_TEMP - DELETE
DELETE
FROM EMPREGADO_TEMP

SELECT *
FROM EMPREGADO_TEMP

DROP TABLE EMPREGADO_TEMP

--RECRIAR A TABELA
SELECT *
INTO EMPREGADO_TEMP
FROM TB_EMPREGADO

--APAGAR O REGISTRO DO FUNCIONARIO JOSE EMANUEL
--CODFUN 73
--CLAUSULA WHERE
DELETE
FROM EMPREGADO_TEMP
WHERE CODFUN = 73

SELECT *
FROM EMPREGADO_TEMP

--ABRIR A TRANSAÇÃO
BEGIN TRAN
--APAGAR OS REGISTROS DO DEPARTAMENTO 2
SELECT * 
FROM EMPREGADO_TEMP
WHERE COD_DEPTO = 2

DELETE
FROM EMPREGADO_TEMP
WHERE COD_DEPTO = 2

ROLLBACK

--EFETIVAR A TRANSAÇÃO
COMMIT
