USE PEDIDOS

--EXPRESSAO CASE PESQUISADA
/*
SINTAXE
CASE 
	WHEN CONDIÇAO_COLUNA THEN EMPRESSAO
	WHEN CONDIÇAO_COLUNA THEN EMPRESSAO
ELSE
	EXPRESSAO
END
*/
--FAZER UMA QUERY PARA RETORNAR O NOME E O SALARIO DO FUNCIONARIO
--CLASSIFICACAO_SALARIAL
--QUANDO SALARIO É NULO ENTAO RETORNA 'N/C'
--QUANDO SALARIO = 500 ENTAO 'SALARIO BAIXO'
--QUANDO SALARIO ENTRE 500 E 3000 'SALARIO MEDIO'
--CASO CONTRARIO 'SALARIO ALTO'
SELECT NOME	
		,SALARIO
		,CLASSIFICACAO_SALARIAL=CASE
								WHEN SALARIO IS NULL THEN 'NÃO CLASSIFICADO'
								WHEN SALARIO = 500 THEN 'SALÁRIO BAIXO'
								WHEN SALARIO BETWEEN 500 AND 3000 THEN 'SALÁRIO MÉDIO'
							ELSE
								'SALÁRIO ALTO'
							END
FROM TB_EMPREGADO
ORDER BY SALARIO 
