USE PEDIDOS

--EXPRESSAO CASE: SIMPLES E PESQUISADA
--EXPRESSAO CASE SIMPLES
/*
CASE COLUNA
	WHEN CONDIÇAO THEN EXPRESSAO
	WHEN CONDIÇAO THEN EXPRESSAO
ELSE
	EXPRESSAO
END
*/
--QUERY PARA RETORNAR O NOME DO FUNCIONARIO, SALARIO, SINDICALIZADO
--SINDICALIZADO: QUANDO 'S' ENTAO SIM, QUANDO 'N', ENTAO NÃO
SELECT NOME	
		,SALARIO
		,SINDICALIZADO
		,CASE SINDICALIZADO
			WHEN 'S' THEN 'SIM'
			WHEN 'N' THEN 'NÃO'
			ELSE
			'N/C'
			END AS SINDICATO
FROM TB_EMPREGADO

SELECT NOME	
		,SALARIO
		,CASE SINDICALIZADO
			WHEN 'S' THEN 'SIM'
			WHEN 'N' THEN 'NÃO'
			ELSE
			'N/C'
			END AS SINDICALIZADO
FROM TB_EMPREGADO
