USE PEDIDOS

--RETORNAR OS FUNCIONARIOS COM OS SEUS RESPECTIVOS DEPARTAMENTOS E OS FUNCIONARIOS QUE NAO TEM DEPARTAMENTO ASSOCIADOS
SELECT NOME	
		,DEPTO
		,SALARIO
FROM TB_EMPREGADO AS EMP
LEFT JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_CARGO=DEPTO.COD_DEPTO
ORDER BY SALARIO

--RETORNAR OS FUNCIONARIOS COM OS SEUS RESPECTIVOS DEPARTAMENTOS E OS DEPARTAMENTOS QUE NÃO ESTAO SENDO ASSOCIADOS NA TB_EMPREGADO
SELECT NOME	
		,DEPTO
		,SALARIO
FROM TB_EMPREGADO AS EMP
RIGHT JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_CARGO=DEPTO.COD_DEPTO
ORDER BY SALARIO

--FULL JOIN
SELECT NOME	
		,DEPTO
		,SALARIO
FROM TB_EMPREGADO AS EMP
FULL JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_CARGO=DEPTO.COD_DEPTO
ORDER BY SALARIO

--OS FUNCIONARIOS QUE POSSUEM CARGOS ASSOCIADOS, OS FUNCIONARIOS QUE NÃO POSSUEM CARGOS ASSOCIADOS E OS CARGOS CADASTRADOS NA TB_CARGO QUE NÃO ESTAO ASSSOCIADOS NA TB_EMPREGADO
SELECT NOME	
		,CARGO
		,SALARIO
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_CARGO AS CARGO
ON EMP.COD_CARGO=CARGO.COD_CARGO
ORDER BY SALARIO
