USE PEDIDOS

--EXIBIR O CUSTO SALARIAL POR DEPARTAMENTO E TRAZER A DESCRIÇÃO DO DEPARTAMENTO
SELECT EMP.COD_DEPTO
		,DEPTO.DEPTO
		,SUM(EMP.SALARIO) AS CUSTO_SALARIAL
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
GROUP BY EMP.COD_DEPTO, DEPTO.DEPTO
ORDER BY CUSTO_SALARIAL DESC

--EXIBIR OS 5 PRIMEIROS DEPARTAMENTO COM MAIOR CUSTO SALARIAL
--CLAUSULA TOP
SELECT TOP 5 EMP.COD_DEPTO
		,DEPTO.DEPTO
		,SUM(EMP.SALARIO) AS CUSTO_SALARIAL
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
GROUP BY EMP.COD_DEPTO, DEPTO.DEPTO
ORDER BY CUSTO_SALARIAL DESC

--CUSTO SALARIAL POR DEPARTAMENTO E TAMBEM OS REGISTROS COM DEPARTAMENTO NULO CASO EXISTIR NULABILIDADE
SELECT EMP.COD_DEPTO
		,DEPTO.DEPTO
		,SUM(EMP.SALARIO) AS CUSTO_SALARIAL
FROM TB_EMPREGADO AS EMP
LEFT JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
GROUP BY EMP.COD_DEPTO, DEPTO.DEPTO
ORDER BY CUSTO_SALARIAL DESC