USE PEDIDOS

--FUNÇOES MATEMATICAS
--RAIZ QUADRADA
SELECT SQRT(25) AS RAIZ_QUADRADA
SELECT SQRT(16) AS RAIZ_QUADRADA

--FUNÇÃO SQUARE
SELECT SQUARE(2) AS QUADRADO
SELECT SQUARE(5) AS QUADRADO
SELECT SQUARE(3) AS QUADRADO

--POWER(VALOR,POTENCIA)
SELECT POWER(2,3) AS VALOR_CUBO
SELECT POWER(2,5) AS VALOR_POTENCIA

--VALOR ABSOLUTO
--FUNÇÃO ABS
SELECT ABS(45) AS VALOR_ABSOLUTO
SELECT ABS(-45) AS VALOR_ABSOLUTO

--FUNÇAO CEILING - RETORNA O PROXIMO NUMERO INTEIRO SE CASA DECIMAL MAIOR QUE ZERO
SELECT CEILING(149.99) AS NUMERO_INTEIRO

SELECT ID_PRODUTO
		,DESCRICAO
		,PRECO_CUSTO
		,CEILING(PRECO_CUSTO) AS PROXIMO_PRECO
FROM TB_PRODUTO
