USE PEDIDOS 

--AGRUPAMENTO 
--CONTAR REGISTROS - CCOUNT
--QUANTIDADE DE REGISTROS DA TABELA EMPREGADO
SELECT COUNT(*) AS QTDE_REGISTROS
FROM TB_EMPREGADO

SELECT COUNT(NOME) AS QTDE_REGISTROS
FROM TB_EMPREGADO

--QUANTIDADE DE REGISTROS NÃO CONSIDERANDO OS VALORES NULOS
SELECT COUNT(COD_DEPTO) AS QTDE_REGISTROS
FROM TB_EMPREGADO

--QUANTIDADE DE DEPARTAMENTOS NA TABELA DE EMPREGADOS SEM DUPLICIDADE
SELECT COUNT(DISTINCT COD_DEPTO) AS QTDE_DEPTOS
FROM TB_EMPREGADO

SELECT APPROX_COUNT_DISTINCT (COD_DEPTO) AS QTDE_DEPTOS
FROM TB_EMPREGADO

--FUNÇÃO DE AGREGAÇÃO COM AGRUPAMENTO
--GROUP BY
--EXIBIR O CUSTO SALARIO POR DEPARTAMENTO
SELECT COD_DEPTO
		,SUM(SALARIO) AS TOTAL_SALARIO
FROM TB_EMPREGADO
WHERE COD_DEPTO IS NOT NULL
GROUP BY COD_DEPTO
ORDER BY TOTAL_SALARIO DESC


