USE PEDIDOS

--FUNÇÃO DE AGREGAÇÃO
/*
SUM - SOMA
AVG - MEDIA
MAX - MAIOR VALOR
MIN - MENOR VALOR
COUNT - CONTAR REGISTROS
*/
--FAZER UMA QUERY PARA RETORNAR A MEDIA SALARIAL DA TABELA TB_EMPREGADO
SELECT AVG(SALARIO) AS MEDIA_SALARIAL
FROM TB_EMPREGADO
--2360.689655

--EXIBIR O MENOR SALARIO DA TB_EMPREGADO
SELECT MIN(SALARIO) AS MENOR_SALARIO
FROM TB_EMPREGADO
--500.00

--EXIBIRT O MAIOR SALARIO DA TB_EMPREGADO
SELECT MAX(SALARIO) AS MAIOR_SALARIO
FROM TB_EMPREGADO
--8300.00

--EXIBIR A QUANTIDADE DE REGISTROS DA TB_EMPREGADO
SELECT COUNT(*) AS QTD_REGISTROS
FROM TB_EMPREGADO
--61

--EXIBIR A MEDIA SALARIAL DO DEPARTAMENTO 2
SELECT AVG(SALARIO) AS MEDIA_SALARIAL
FROM TB_EMPREGADO
WHERE COD_DEPTO = 2
--2428.750000

---EXIBIR O MENOR SALARIO DO DEPARTAMENTO 7
SELECT MIN(SALARIO) AS MENOR_SALARIO
FROM TB_EMPREGADO
WHERE COD_DEPTO = 7
--1200.00

---EXIBIR O MAIOR SALARIO DO DEPARTAMENTO 7
SELECT MAX(SALARIO) AS MAIOR_SALARIO
FROM TB_EMPREGADO
WHERE COD_DEPTO = 7

SELECT * 
FROM TB_EMPREGADO
WHERE COD_DEPTO = 7

--EXIBIR O MENOR SALARIO DO DEPARTAMENTO 3
SELECT MIN(SALARIO) AS MENOR_SALARIO
FROM TB_EMPREGADO
WHERE COD_DEPTO = 3

--EXIBIR O MENOR SALARIO DO DEPARTAMENTO 3
SELECT MAX(SALARIO) AS MAIOR_SALARIO
FROM TB_EMPREGADO
WHERE COD_DEPTO = 3


--EXIBIR FUNCIONARIOS DO DEPARTAMENTO 3
SELECT *
FROM TB_EMPREGADO
WHERE COD_DEPTO = 3
ORDER BY SALARIO
