USE PEDIDOS

--CHARINDEX -> RETORNA A POSIÇÃO DE UM CARACTERE QUE ESTAMOS BUSCANDO
SELECT CHARINDEX('PA','IMPALA') AS POSICAO_TEXTO

SELECT NOME
	,CHARINDEX ('TR',NOME) AS POSICAO_NOME
FROM TB_EMPREGADO
ORDER BY NOME

--REPLACE -> SUBSTITUIÇÃO DE UM CARACTERE
SELECT REPLACE ('GUARDA&SOL','&','-') AS NOME

--FAZER UMA QUERY PARA RETORNAR O NOME E O SALARIO DO FUNCIONARIO
--EXIBIR O SALARIO COM VIRGULA NAS CASAS DECIMAIS
SELECT NOME
		,REPLACE(SALARIO,'.',',') AS SALARIO
FROM TB_EMPREGADO

--FUNÇAO PARA ELIMINAR ESPAÇO EM BRANCO
--LTRIM/RTRIM
SELECT ('     GUARDA-SOL') AS TEXTO
		,LTRIM('     GUARDA-SOL') AS TEXTO_SEM_ESPACO

SELECT ('GUARDA-       ')+'SOL' AS TEXTO
		,RTRIM('GUARDA-       ')+'SOL' AS TEXTO_SEM_ESPACO

