USE PEDIDOS

--FUNÇÃO DE DATA
--DATEDIFF
--DIAS VIVIDOS
SELECT DATEDIFF(DAY, '2023/11/30', GETDATE()) AS DIAS_VIVIDOS

--MES VIVIDOS
SELECT DATEDIFF(MONTH, '2023/11/30', GETDATE()) AS MESES_VIVIDOS

--ANOS VIVIDOS
SELECT DATEDIFF(YEAR, '2020/12/08', GETDATE()) AS ANOS_VIVIDOS

SELECT NOME
		,DATA_NASCIMENTO
		,DATEDIFF(YEAR, DATA_NASCIMENTO, GETDATE()) AS IDADE
FROM TB_EMPREGADO
ORDER BY IDADE

--EOMONTH RETORNA O ULTIMO DIA DO MES DE UMA DETERMINADA DATA
SELECT EOMONTH('2023/11/10') AS DATA_ULTIMO_DIA_MES

SELECT EOMONTH('2023/03/22') AS DATA_ULTIMO_DIA_MES

--WEEK -RETORNA SEMANA DO ANO
SELECT DATEPART(WEEK, GETDATE()) AS QTDE_SEMANAS

--WEEKDAY - RETORNA O DIA DA SEMANA EM NUMERO
SELECT DATEPART(WEEKDAY,GETDATE()) AS DIA_SEMANA

--DATEPARTE
--SINTAXE
--DATEPART(<EXPRESSAO>,DATA)
-- <EXPRESSAO>= DAY, MONTH, YEAR, WEEK, WEEKDAY
SELECT DATEPART(DAY, '2023/12/11') AS DIA
