USE PEDIDOS

--FUNÇOES DE TEXTO
--LEFT/RIGHT

SELECT *
FROM TB_CLIENTE

--FAZER UMA QUERY PARA RETORNAR O NOME DO CLIENTE, ENDEREÇO  E CEP
--O CEP DEVE SER RETORNADO EM DUAS COLUNAS, SENDO A COLUNA REGIAO COM OS 5 PRIMEIROS CARACTERES E A COLUNA DISTRIBUIÇAO COM OS 3 ULTIMOS CARACTERES
SELECT NOME, ENDERECO, CEP, LEFT(CEP,5) AS REGIAO, RIGHT (CEP,3) AS DISTRIBUIÇAO
FROM TB_CLIENTE

--LEN RETORNA A QUANTIDADE DE CARACTERES OCUPADOS EM UMA COLUNA
SELECT NOME, LEN(NOME) AS QTDE_NOME
		,CEP, LEN(CEP) AS QTDE_CEP
FROM TB_CLIENTE

--VISUALIZAR A ESTRUTURA DA TABELA CLIENTE
EXEC SP_HELP TB_CLIENTE

--FUNÇAO LEN E NULABILIDADE
SELECT NOME, LEN(NOME) AS QTDE_NOME
		,ISNULL (CEP,'N/C') AS CEP, LEN(ISNULL (CEP,'N/C')) AS QTDE_CEP
FROM TB_CLIENTE
ORDER BY CEP

--COLOCAR 0 ONDE O CEP É NULO
SELECT NOME
		,LEN(NOME) AS QTDE_NOME
		,ISNULL (CEP,'N/C') AS CEP
		,ISNULL(LEN(CEP),0) AS QTDE_CEP
FROM TB_CLIENTE
ORDER BY CEP

--ANALISE DAS COLUNAS REGIAO E DISTRIBUIÇAO
SELECT NOME
		, ENDERECO
		, CEP
		, LEFT (ISNULL(CEP,'N/C'),5) AS REGIAO
		, RIGHT (ISNULL (CEP,'N/C'),3) AS DISTRIBUIÇAO
FROM TB_CLIENTE
ORDER BY CEP

--SUBSTRING
--FAZER UMA QUERY PARA RETORNAR O NOME DO CLIENTE, ENDEREÇO  E CEP
--O CEP DEVE SER RETORNADO EM DUAS COLUNAS, SENDO A COLUNA REGIAO COM OS 5 PRIMEIROS CARACTERES E A COLUNA DISTRIBUIÇAO COM OS 3 ULTIMOS CARACTERES
--EXEMPLO CEP= 02530000
SELECT NOME
		,ENDERECO
		,CEP
		,SUBSTRING (CEP,1,5) AS REGIAO
		,SUBSTRING (CEP,6,3) AS DISTRIBUIÇÃO
FROM TB_CLIENTE
ORDER BY CEP