USE SISTEMA_PEDIDOS

SELECT *
FROM TB_EMPREGADO

SELECT *
FROM TB_DEPARTAMENTO

--FAZER UMA QUERY PARA RETORNAR O NOME DO FUNCIONARIO, O CODIGO DO DEPARTAMENTO, O NOME DO DEPARTAMENTO E O SALARIO
SELECT NOME AS NOME_EMPREGADO	
		,DEPTO AS DEPARTAMENTO
		,SALARIO
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO

SELECT NOME AS NOME_EMPREGADO	
		,DEPTO AS DEPARTAMENTO
		,SALARIO
		,EMP.COD_DEPTO
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
