USE PEDIDOS

--OPERADOR E CCONJUNTO INTERSECT
--CRIAR UMA TABELA COM O NOME TB_MAIOR_SALARIO FROM TB_EMPREGADO
SELECT COD_DEPTO
		,NOME
		,DATA_ADMISSAO
		,SALARIO
INTO TB_MAIOR_SALARIO
FROM TB_EMPREGADO
WHERE SALARIO > 5000

SELECT *
FROM TB_MAIOR_SALARIO

--COMPARAR DUAS CONSULTAS
--QUERY NA TABELEA TB_EMPREGADO E A QUERY NA TABELA TB_MAIOR_SALARIO
SELECT COD_DEPTO
		,NOME,SALARIO
FROM TB_EMPREGADO
INTERSECT
SELECT COD_DEPTO
		,NOME,SALARIO
FROM TB_MAIOR_SALARIO
