USE PEDIDOS 

--FAZER UMA QUERY PARA RETORNAR O NUMERO DO PEDIDO, O NOME DO CLIENTE QUE FEZ O PEDIDO
--O NOME DO VENDEDOR QUE EMITIU O PEDIDO A DATA DE EMISSAO DO PEDIDO, A DESCRIÇÃO DO PRODUTO
--ESTA QUERY DEVE RETORNAR OS PEDIDOS DO PERIODO DE JAN/2016
SELECT PED.NUM_PEDIDO
		,CLI.NOME AS NOME_CLIENTE
		,VEND.NOME AS NOME_VENDEDOR
		,PED.DATA_EMISSAO
		,PROD.DESCRICAO
FROM TB_PEDIDO AS PED
INNER JOIN TB_CLIENTE AS CLI
ON PED.CODCLI=CLI.CODCLI
INNER JOIN TB_VENDEDOR AS VEND
ON PED.CODVEN=VEND.CODVEN
INNER JOIN TB_ITENSPEDIDO AS ITEM
ON ITEM.NUM_PEDIDO=PED.NUM_PEDIDO
INNER JOIN TB_PRODUTO AS PROD
ON ITEM.ID_PRODUTO=PROD.ID_PRODUTO
WHERE PED.DATA_EMISSAO BETWEEN '2016/01/01' AND '2016/01/31'
