USE PEDIDOS

--MERGE

--CRIAR UMA COPIA DA TABELA DE EMPREGADO COM O NOME EMP_PROD
SELECT *
INTO EMP_PROD
FROM TB_EMPREGADO

SELECT * FROM TB_EMPREGADO

SELECT * FROM EMP_PROD

--APAGAR OS REGISTROS DE COD_CARGO = 3
DELETE FROM EMP_PROD
WHERE COD_CARGO = 3

SET IDENTITY_INSERT EMP_PROD ON

MERGE EMP_PROD AS EMPPROD
USING TB_EMPREGADO AS EMP
ON EMPPROD.CODFUN=EMP.CODFUN

WHEN MATCHED AND EMPPROD.SALARIO <> EMP.SALARIO THEN
	UPDATE
	SET EMPPROD.SALARIO=EMP.SALARIO
WHEN NOT MATCHED THEN
	INSERT(
	CODFUN
,NOME
,NUM_DEPEND
,DATA_NASCIMENTO
,COD_DEPTO
,COD_CARGO
,DATA_ADMISSAO
,SALARIO
,PREMIO_MENSAL
,SINDICALIZADO
,OBS
,FOTO
	)
	VALUES(
	CODFUN
,NOME
,NUM_DEPEND
,DATA_NASCIMENTO
,COD_DEPTO
,COD_CARGO
,DATA_ADMISSAO
,SALARIO
,PREMIO_MENSAL
,SINDICALIZADO
,OBS
,FOTO)
WHEN NOT MATCHED BY SOURCE THEN
DELETE
OUTPUT $ACTION AS [ACAO],INSERTED.CODFUN AS CODIGO_ATUAL
,DELETED.CODFUN AS CODIGO_ANTERIOR
,INSERTED.NOME AS NOME_ATUAL
,DELETED.NOME AS NOME_ANTERIOR
,INSERTED.SALARIO AS SALARIO_ATUAL
,DELETED.SALARIO AS SALARIO_ANTERIOR;

SELECT * FROM EMP_PROD

SET IDENTITY_INSERT EMP_PROD OFF
