USE PEDIDOS

--OPERADORES LOGICOS
/*
AND  COMBINA DUAS EXPRESSOES E EXIGE QUE SEJAM VERDADEIRAS PARA QUE O REGISTRO SEJA APRESENTADO
OR   COMBINA DUAS EXPRESSOES E EXIGE QUE PELO MENOS UMA EXPRESSAO SEJA VERDADEIRA PARA QUE O REGISTRO SEJA RETORNADO
NOT  INVERTER O RESULTADO LOGICO DA EXPRESSAO A DIREITA, OU SEJA SE A EXPRESSAO É VERDADEIRA, ELE RETORNA FALSO E VICE VERSA
*/

--LISTAR OS FUNCIONARIOS DO DEPARTAMENTO 2 E COM SALARIO MAIOR QUE 5000
SELECT NOME, SALARIO, COD_DEPTO
FROM TB_EMPREGADO
WHERE COD_DEPTO = 2 
AND
SALARIO >=5000

--LISTAR OS FUNCIONARIOS DO DEPARTAMENTO 2 OU OS FUNCIONARIOS COM SALARIO MAIOR QUE 5000
SELECT NOME, SALARIO, COD_DEPTO
FROM TB_EMPREGADO
WHERE COD_DEPTO = 2 
OR
SALARIO > 5000
ORDER BY COD_DEPTO

--LISTAR OS FUNCIONARIOS QUE PERTENCEM AO DEPARTAMENTO IGUAL A 3
SELECT *
FROM TB_EMPREGADO
WHERE COD_DEPTO = 3

