USE PEDIDOS

--CONSULTAR A TABELA TB_EMPREGADO RETORNANDO AS COLUNAS NOME, SALARIO, ORDENANDO O NOME EM ORDEM ASC
SELECT NOME, SALARIO
FROM TB_EMPREGADO
ORDER BY NOME ASC

--ORDENAR POR POSIÇÃO
SELECT NOME, SALARIO
FROM TB_EMPREGADO
ORDER BY 1

--ORDENAR POR POSIÇÃO DA COLUNA SALARIO
SELECT NOME, SALARIO
FROM TB_EMPREGADO
ORDER BY 2

--ORDENAR A COLUNA SALARIO EM ORDEM DESC
SELECT NOME, SALARIO 
FROM TB_EMPREGADO
ORDER BY 2 DESC

--ORDENAR POR DUAS COLUNAS OU CAMPOS
--FAZER UMA QUERY PARA RETORNAR O CODDEPTO, NOME E SALARIO
SELECT COD_DEPTO, NOME, SALARIO
FROM TB_EMPREGADO
ORDER BY COD_DEPTO

--ORDENAÇÃO DA COLUNA NOME EM ORDEM DESC
SELECT COD_DEPTO, NOME, SALARIO
FROM TB_EMPREGADO
ORDER BY COD_DEPTO, NOME DESC

--ORDENAR POR COD_DEPTO SEGUIDO DA COLUNA SALARIO DO MAIOR PARA O MENOR
SELECT COD_DEPTO, NOME, SALARIO
FROM TB_EMPREGADO
ORDER BY COD_DEPTO, SALARIO DESC

