USE PEDIDOS

--QUERY DINAMICA
SELECT * 
FROM TB_PRODUTO

--ARMAZENAR A QUERY EM UMA VARIAVEL
DECLARE @SQL VARCHAR(300)
SET @SQL ='SELECT * FROM TB_PRODUTO'
--EXECUTAR A VARIAVEL @SQL Q CONTEM A QUERY
EXEC(@SQL)

--CRIAR UMA QUERY PARA RETORNAR O NUM_PEDIDO, O NOME DO CLIENTE, O PRODUDO, A DESCRICAO DO PRODUTO E A QUANTIDADE
DECLARE @QUERYPED VARCHAR(1000)
SET @QUERYPED='SELECT PED.NUM_PEDIDO	
		,CLI.NOME AS NOME_CLIENTE
		,ITEM.QUANTIDADE
		,ITEM.ID_PRODUTO
		,PROD.DESCRICAO
FROM TB_PEDIDO AS PED
INNER JOIN TB_CLIENTE AS CLI
ON PED.CODCLI=CLI.CODCLI
INNER JOIN TB_ITENSPEDIDO AS ITEM
ON ITEM.NUM_PEDIDO=PED.NUM_PEDIDO
INNER JOIN TB_PRODUTO AS PROD
ON ITEM.ID_PRODUTO=PROD.ID_PRODUTO'
EXEC(@QUERYPED)
