USE PEDIDOS

SELECT *
FROM TB_PEDIDO

--FAZER UMA QUERY PARA EXIBIR AS COLUNAS NUM_PEDIDO, DATA_EMISSAO, VLR_TOTAL, TOTAL_DE_VENDAS(2016)
SELECT SUM(VLR_TOTAL)
FROM TB_PEDIDO
WHERE YEAR(DATA_EMISSAO)=2016


SELECT NUM_PEDIDO
		,DATA_EMISSAO
		,VLR_TOTAL
		,(SELECT SUM(VLR_TOTAL)
			FROM TB_PEDIDO
			WHERE YEAR(DATA_EMISSAO)=2016) AS TOTAL_VENDAS_2016
FROM TB_PEDIDO
WHERE YEAR(DATA_EMISSAO)=2016

--ARMAZENAR O RESULTADO DA QUERY ACIMA EM UMA TABELA COM O NOME TOTAL_VENDAS_2016
SELECT NUM_PEDIDO
		,DATA_EMISSAO
		,VLR_TOTAL
		,(SELECT SUM(VLR_TOTAL)
			FROM TB_PEDIDO
			WHERE YEAR(DATA_EMISSAO)=2016) AS TOTAL_VENDAS_2016
INTO TOTAL_VENDAS_2016
FROM TB_PEDIDO
WHERE YEAR(DATA_EMISSAO)=2016

SELECT NUM_PEDIDO
		,DATA_EMISSAO
		,VLR_TOTAL
		,VLR_TOTAL/TOTAL_VENDAS_2016 AS PERCENTUAL
FROM TOTAL_VENDAS_2016

--CALCULO DO PERCENTUAL NA PROPRIA QUERY
SELECT NUM_PEDIDO
		,DATA_EMISSAO
		,VLR_TOTAL
		,(VLR_TOTAL/(SELECT SUM(VLR_TOTAL)
			FROM TB_PEDIDO
			WHERE YEAR(DATA_EMISSAO)=2016)) AS PERCENTUAL
FROM TB_PEDIDO
WHERE YEAR(DATA_EMISSAO)=2016

