USE SISTEMA_PEDIDOS


EXEC SP_HELP TB_EMPREGADO

INSERT INTO TB_EMPREGADO (CODFUN
						,NOME
						,NUM_DEPEND
						,DATA_NASCIMENTO
						,COD_DEPTO
						,COD_CARGO
						,DATA_ADMISSAO
						,SALARIO
						,PREMIO_MENSAL
						,OBS
						,FOTO
						,COD_SUPERVISOR
						,CPF)
VALUES(5,'JOAO LIMA MACHADO DA SILVA',3
		,'1955/10/30',4,3
		,'1993/01/10'
		,3000
		,800
		,'N/A'
		,'N/A'
		,1
		,15632613276)

SELECT *
FROM TB_EMPREGADO

--TESTAR A CONSTRAINT CHECK NA COLUNA SINDICALIZADO
INSERT INTO TB_EMPREGADO (CODFUN
						,NOME
						,NUM_DEPEND
						,DATA_NASCIMENTO
						,COD_DEPTO
						,COD_CARGO
						,DATA_ADMISSAO
						,SALARIO
						,PREMIO_MENSAL
						,SINDICALIZADO
						,OBS
						,FOTO
						,COD_SUPERVISOR
						,CPF)
VALUES(6,'CARLOS ALBERTO DA SILVA',0
		,'1961/06/07',4,3
		,'1987/10/01'
		,4500
		,1199.53
		,'N'
		,'N/A'
		,'N/A'
		,2
		,87432507501)

SELECT *
FROM TB_EMPREGADO