USE SISTEMA_PEDIDOS

--FAZER UMA QUERY NA TABELA TB_DEPENDENTE
SELECT *
FROM TB_DEPENDENTE

--VISUALIZAR A ESTRUTURA DA TB_DEPENDENTE
EXEC SP_HELP TB_DEPENDENTE

-- INSERIR UM REGISTRO NA TABELA TB_DEPENDENTE
INSERT INTO TB_DEPENDENTE(CODFUN,NOME,DATA_NASCIMENTO)
VALUES(1,'PEDRO','1987/10/01')

--INSERIR O SEGUNDO REGISTRO
INSERT INTO TB_DEPENDENTE(CODFUN,NOME,DATA_NASCIMENTO)
VALUES(2,'CARLOS','1988/01/10')

SELECT *
FROM TB_DEPENDENTE

--INSERIR O TERCEIRO REGISTRO
INSERT INTO TB_DEPENDENTE(CODFUN,NOME,DATA_NASCIMENTO)
VALUES(2,'ALBERTO','1990/07/20')
