USE SISTEMA_PEDIDOS

--VISUALIZAR A ESTRUTURA DA TB_DEPARTAMENTO
EXEC SP_HELP TB_DEPARTAMENTO

SELECT *
FROM TB_DEPARTAMENTO

--INSERT DECLARATIVO
--CHAVE DUPLICADA
INSERT INTO TB_DEPARTAMENTO(COD_DEPTO,DEPTO)
VALUES(4,'PRODUÇÃO')

--SCRIPT CORRETO
INSERT INTO TB_DEPARTAMENTO(COD_DEPTO,DEPTO)
VALUES(5,'PRODUÇÃO')

--TESTAR O COD_CARGO NA TB_CARGO
SELECT * 
FROM TB_CARGO
INSERT INTO TB_CARGO(COD_CARGO, CARGO, SALARIO_INIC)
VALUES(5,'VENDEDOR(A)',500)

--VISUALIZAR A ESTRUTURA DA TABELA TB_CARGO
EXEC SP_HELP TB_CARGO

--TESTAR A CONSTRAINT DE CHECK NA COLUNA SALARIO_INIC
--INSERT POSICIONAL
INSERT INTO TB_CARGO
VALUES(6,'REPRESENTANTE DA DIREÇÃO',-890)

--SCRIPT CORRIGIDO
INSERT INTO TB_CARGO
VALUES(6,'REPRESENTANTE DA DIREÇÃO',890)