USE PEDIDOS 

--UPDATE COM SUBQUERY
--ATUALIZAR EM 10% O SALARIO DOS FUNCIONARIOS DO DEPARTAMENTO C.P.D/ COD_DEPTO =2
SELECT * 
FROM EMPREGADO_TEMP
WHERE COD_DEPTO=2

SELECT *
FROM TB_DEPARTAMENTO

UPDATE EMPREGADO_TEMP
SET SALARIO = SALARIO * 1.10
WHERE COD_DEPTO = (SELECT COD_DEPTO 
					FROM TB_DEPARTAMENTO 
					WHERE DEPTO = 'C.P.D.')

SELECT COD_DEPTO 
FROM TB_DEPARTAMENTO 
WHERE DEPTO = 'C.P.D.'

--UPDATE COM JOIN
UPDATE EMPREGADO_TEMP
SET SALARIO = SALARIO * 1.10
FROM EMPREGADO_TEMP AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
WHERE DEPTO.DEPTO='C.P.D.'

SELECT * 
FROM EMPREGADO_TEMP
WHERE COD_DEPTO = 2
