USE PEDIDOS

--UPDATE COM TOP
SELECT *
FROM EMPREGADO_TEMP

DROP TABLE EMPREGADO_TEMP

SELECT * 
INTO EMPREGADO_TEMP
FROM TB_EMPREGADO

SELECT *
FROM EMPREGADO_TEMP

--ATUALIZAR EM 10% O SALARIO DOS 5 PRIMEIROS FUNCIONARIOS
BEGIN TRAN

UPDATE TOP(5) EMPREGADO_TEMP
SET SALARIO = SALARIO * 1.10

SELECT * 
FROM EMPREGADO_TEMP

ROLLBACK --VOLTA A TRANSAÇAO

--UPDATE COM  OUTPUT
--ATUALIZAR O SALARIO EM 10% DOS FUNCIONARIOS DO DEPARTAMENTO 2
BEGIN TRAN
UPDATE EMPREGADO_TEMP
SET SALARIO = SALARIO * 1.10
OUTPUT inserted.CODFUN, inserted.NOME
		,deleted.SALARIO AS SALARIO_ANTERIOR
		,inserted.SALARIO AS SALARIO_ATUAL
WHERE COD_DEPTO = 2

COMMIT

SELECT * 
FROM EMPREGADO_TEMP
WHERE COD_DEPTO = 2
