USE PEDIDOS

--CRIAR UM SCRIPT PARA LER O NOME DO FUNCIONARIO E RETORNAR SOMENTE O PRIMEIRO NOME
SELECT NOME
FROM TB_EMPREGADO

--CRIAR UMA TABELA COM O NOME 
SELECT * 
INTO EMPREGADO_TEMP
FROM TB_EMPREGADO

--ATUALIZAR O NOME OLAVO TRINDADE PARA OLAVO
UPDATE EMPREGADO_TEMP
SET NOME='OLAVO'
WHERE CODFUN=1

SELECT *
FROM EMPREGADO_TEMP

DECLARE @CODEMP INT
		,@NOME CHAR(10)
SET @CODEMP = 5
SELECT @NOME = SUBSTRING(NOME,1,CHARINDEX(' ',NOME))
FROM EMPREGADO_TEMP
WHERE CODFUN=@CODEMP
SELECT @NOME AS PRIMEIRO_NOME

SELECT NOME
		,CHARINDEX(' ',NOME) AS POSICAO
		,SUBSTRING(NOME,1,CHARINDEX(' ',NOME))
FROM EMPREGADO_TEMP

--EXIBIR O NOME QUANDO A POSIÇAO DO ESPAÇO FOR  = 0

DECLARE @CODEMP INT
		,@NOME CHAR(10)
SET @CODEMP = 12
SELECT @NOME = CASE CHARINDEX(' ',NOME)
				WHEN 0 THEN NOME
				ELSE SUBSTRING(NOME,1,CHARINDEX(' ',NOME))
				END
FROM EMPREGADO_TEMP
WHERE CODFUN=@CODEMP
SELECT @NOME AS PRIMEIRO_NOME
