USE PEDIDOS

--FAZER UM SCRIPT COM VARIAVEL E CASE
-- CRIAR UM SCRIPT PARAR RECEBER UMA DATA E DEVE EXIBIR O DIA DA SEMANA POR EXTENSO
DECLARE @DATA DATE
		,@DIA INT
SET @DATA='2024/01/11'
SET @DIA = DATEPART(WEEKDAY,@DATA)
SELECT CASE @DIA	
			WHEN 1 THEN 'DOMINGO'
			WHEN 2 THEN 'SEGUNDA-FEIRA'
			WHEN 3 THEN 'TERÇA-FEIRA'
			WHEN 4 THEN 'QUARTA-FEIRA'
			WHEN 5 THEN 'QUINTA-FEIRA'
			WHEN 6 THEN 'SEXTA-FEIRA'
			WHEN 7 THEN 'SABADO'
			END AS DIA_SEMANA
