USE PEDIDOS	

CREATE VIEW VW_DADOS_EMP
AS
SELECT NOME
		,COD_DEPTO
		,SALARIO
FROM TB_EMPREGADO
WHERE COD_DEPTO IN(2,5,8,11)

--CONSULTAR A VIEW VW_DADOS_EMP
SELECT*
FROM VW_DADOS_EMP
ORDER BY COD_DEPTO DESC

--CRIAR UMA VISAO UNINDO DUAS TABELAS
CREATE VIEW VW_EMPREGADO_DEPTONULL
AS
SELECT EMP.NOME
		,EMP.COD_DEPTO
		,DEPTO.DEPTO
		,EMP.SALARIO
FROM TB_EMPREGADO AS EMP
LEFT JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO

--ORDER BY EM VIEW NÃO É PERMITIDO
--VIEW NÃO ACEITA VARIAVEL
SELECT *
FROM VW_EMPREGADO_DEPTONULL
ORDER BY COD_DEPTO

--APAGAR A VIEW
DROP VIEW VW_EMPREGADO_DEPTONULL

