USE PEDIDOS
--1a. Preparar a tabela TEMP_CARGO para realizar o exercício:
--Criar a tabela TEMP_CARGO a partir da tabela TB_CARGO.
SELECT *
INTO TEMP_CARGO
FROM TB_CARGO
SELECT * FROM TB_CARGO

--Apagar os registros com código do cargo 5,9,10 da tabela TEMP_CARGO.
DELETE
FROM TEMP_CARGO
WHERE COD_CARGO IN (5,9,10)

--Atualizar em 10% o SALARIO_INIC dos códigos de cargo 4 e 12.
UPDATE TEMP_CARGO
SET SALARIO_INIC=SALARIO_INIC *1.10
WHERE COD_CARGO IN (4,12)

/*
Criar um script para comparar as tabelas TEMP_CARGO e TB_CARGO e realizar os passos:
• Atualizar a coluna SALARIO_INIC com o SALARIO_INIC da tabela TB_CARGO quando estiverem diferentes.
• Inserir, na tabela TEMP_CARGO, os registros de cargo quando este não existir na tabela.
*/
SET IDENTITY_INSERT TEMP_CARGO ON
MERGE TEMP_CARGO AS EMPCARGO --TABELA ALVO
USING TB_CARGO AS CARGO --TABELA FONTE
ON EMPCARGO.COD_CARGO=CARGO.COD_CARGO
WHEN MATCHED AND EMPCARGO.SALARIO_INIC <> CARGO.SALARIO_INIC THEN
    UPDATE
    SET EMPCARGO.SALARIO_INIC=CARGO.SALARIO_INIC
WHEN NOT MATCHED THEN
    INSERT(COD_CARGO,CARGO,SALARIO_INIC)
    VALUES(COD_CARGO,CARGO,SALARIO_INIC);
SET IDENTITY_INSERT TEMP_CARGO OFF

/*
. Criar um script para manter os dados abaixo em memória:
• NUM_PEDIDO
• NOME DO CLIENTE
• DATA_EMISSAO
• VLR_TOTAL
*/
WITH DADOS_PED
AS
(SELECT PED.NUM_PEDIDO
       ,CLI.NOME
       ,PED.DATA_EMISSAO
       ,PED.VLR_TOTAL
FROM TB_PEDIDO AS PED
INNER JOIN TB_CLIENTE AS CLI
ON PED.CODCLI=CLI.CODCLI)
SELECT *
FROM DADOS_PED

/*
Criar uma visão para exibir:
• NUM_PEDIDO
• DATA_EMISSAO
• NOME DO CLIENTE
*/
CREATE VIEW VW_COMPRAS_CLIENTE
WITH SCHEMABINDING
AS
SELECT NUM_PEDIDO
      ,DATA_EMISSAO
      ,CLI.NOME AS NOME_CLIENTE
FROM DBO.TB_PEDIDO AS PED
INNER JOIN DBO.TB_CLIENTE AS CLI
ON PED.CODCLI=CLI.CODCLI

--Criar um índice para a view criada no exercício anterior, para a coluna NUM_PEDIDO.
CREATE UNIQUE CLUSTERED INDEX NDX_NUMPED
ON VW_COMPRAS_CLIENTE(NUM_PEDIDO)