USE PEDIDOS

--Fazer uma query para retornar NUM_PEDIDO, DATA_EMISSAO e VLR_TOTAL da tabela TB_PEDIDO, seguidos de NOME do vendedor da tabela TB_VENDEDOR.
SELECT PED.NUM_PEDIDO
		,PED.DATA_EMISSAO
		,PED.VLR_TOTAL
		,VEND.NOME
FROM TB_PEDIDO AS PED
INNER JOIN TB_VENDEDOR AS VEND
ON VEND.CODVEN = PED.CODVEN

--Fazer uma query para retornar os itens de pedido (TB_ITENSPEDIDO) com o nome do produto (TB_PRODUTO.DESCRICAO).
SELECT ITEM.*
		,PROD.DESCRICAO
FROM TB_ITENSPEDIDO AS ITEM
INNER JOIN TB_PRODUTO AS PROD
ON PROD.ID_PRODUTO = ITEM.ID_PRODUTO

--Fazer uma query para retornar os itens de pedidos, o nome do produto e a cor (TB_COR).
SELECT ITEM.*
		,PROD.DESCRICAO
		,COR.COR
FROM TB_ITENSPEDIDO AS ITEM
INNER JOIN TB_PRODUTO AS PROD
ON PROD.ID_PRODUTO = ITEM.ID_PRODUTO
INNER JOIN TB_COR AS COR
ON COR.CODCOR = ITEM.CODCOR

--Fazer uma query para retornar as colunas ID_PRODUTO e DESCRICAO da tabela TB_PRODUTO, seguidos da descrição do tipo de produto (TB_TIPOPRODUTO.TIPO) e do nome da unidade de medida (TB_UNIDADE.UNIDADE).
SELECT PROD.ID_PRODUTO
		,PROD.DESCRICAO
		,TIPO.TIPO
		,UNID.UNIDADE
FROM TB_PRODUTO AS PROD
INNER JOIN TB_TIPOPRODUTO AS TIPO
ON TIPO.COD_TIPO = PROD.COD_TIPO
INNER JOIN TB_UNIDADE AS UNID
ON PROD.COD_UNIDADE=UNID.COD_UNIDADE

--Fazer uma query para retornar os pedidos (TB_PEDIDO) do vendedor MARCELO em Janeiro de 2017.
SELECT PED.DATA_EMISSAO
		,PED.NUM_PEDIDO
		,VEND.NOME
FROM TB_PEDIDO AS PED
INNER JOIN TB_VENDEDOR AS VEND
ON PED.CODVEN=VEND.CODVEN
WHERE VEND.NOME ='MARCELO'
AND YEAR(DATA_EMISSAO) = 2017
AND MONTH(DATA_EMISSAO) = 1

--Fazer uma query para retornar o NUM_PEDIDO, VLR_TOTAL (PEDIDOS) e NOME (TB_CLIENTE). Mostre apenas pedidos de janeiro de 2017 do estado de SP.
SELECT PED.NUM_PEDIDO
		,PED.VLR_TOTAL
		,CLI.NOME
FROM TB_PEDIDO AS PED
INNER JOIN TB_CLIENTE AS CLI
ON CLI.CODCLI = PED.CODCLI
AND YEAR(PED.DATA_EMISSAO) = 2017
AND MONTH(PED.DATA_EMISSAO) = 1
AND CLI.ESTADO ='SP'

--Fazer uma query para retornar o número do pedido e o valor dos pedidos de cor VERDE de 2012.
SELECT ITEM.NUM_PEDIDO
		,PED.VLR_TOTAL
		,YEAR(PED.DATA_EMISSAO) AS ANO
FROM TB_ITENSPEDIDO AS ITEM
INNER JOIN TB_PEDIDO AS PED
ON PED.NUM_PEDIDO = ITEM.NUM_PEDIDO
INNER JOIN TB_COR AS COR
ON COR.CODCOR = ITEM.CODCOR
WHERE COR.COR ='VERDE'
AND YEAR(PED.DATA_EMISSAO) = 2012
