USE PEDIDOS

--Apresentar os cargos que não possuem associação na tabela de empregado.
SELECT COD_CARGO
FROM TB_CARGO
EXCEPT
SELECT COD_CARGO
FROM TB_EMPREGADO

--Criar a tabela TB_MAIOR_SALARIO.
/*
• COD_DEPTO
• NOME
• DATA_NASCIMENTO
• TABELA TB_EMPREGADO
• FILTRO SALARIO>5000
*/
SELECT COD_DEPTO
      ,NOME
      ,DATA_NASCIMENTO
INTO TB_MAIOR_SALARIO
FROM TB_EMPREGADO
WHERE SALARIO>5000

--Usando a tabela TB_MAIOR_SALARIO, exiba os registros que são comuns para as tabelas TB_MAIOR_SALARIO e TB_EMPREGADO.
SELECT COD_DEPTO
      , NOME
      , DATA_NASCIMENTO
FROM TB_EMPREGADO
INTERSECT
SELECT COD_DEPTO
      , NOME
      , DATA_NASCIMENTO
FROM TB_MAIOR_SALARIO

--Exibir a coluna NOME da tabela TB_EMPREGADO e a coluna NOME da tabela TB_VENDEDOR no mesmo result set (resultado da query).
SELECT NOME, 'EMPREGADO' AS TABELA
FROM TB_EMPREGADO
UNION
SELECT NOME, 'VENDEDOR'
FROM TB_VENDEDOR
ORDER BY TABELA

-- Exibir a coluna NOME da tabela TB_EMPREGADO e a coluna NOME da tabela TB_MAIOR_SALARIO.
--O resultado deve manter os registros duplicados.
SELECT NOME AS EMPREGADO
FROM TB_EMPREGADO
UNION ALL
SELECT NOME AS EMP_MAIOR_SALARIO
FROM TB_MAIOR_SALARIO
ORDER BY 1

/*
Crie os seguintes UDDTs.
• TIPO_CODIGO INT NOT NULL
• TIPO_ENDERECO VARCHAR(60) NOT NULL
• TIPO_FONE CHAR(14) NULL
• TIPO_SEXO CHAR(1) NOT NULL
• TIPO_ALIQUOTA NUMERIC(4,2) NULL
• TIPO_PRAZO INT NOT NULL
*/
CREATE TYPE TIPO_CODIGO
FROM INT NOT NULL;

CREATE TYPE TIPO_ENDERECO
FROM VARCHAR(60) NOT NULL;

CREATE TYPE TIPO_FONE
FROM CHAR(14) NULL;

CREATE TYPE TIPO_SEXO
FROM CHAR(1) NOT NULL;

CREATE TYPE TIPO_ALIQUOTA
FROM NUMERIC(4,2) NULL;

CREATE TYPE TIPO_PRAZO
FROM INT NOT NULL;

/*
Crie a tabela PESSOAS, seguindo o modelo adiante:
• PESSOAS
• COD_PESSOA TIPO_CODIGO autonumeração chave primária
• NOME VARCHAR(30)
• ENDERECO TIPO_ENDERECO
• SEXO TIPO_SEXO
*/
CREATE TABLE PESSOAS
( COD_PESSOA TIPO_CODIGO IDENTITY(1,1) PRIMARY KEY
      ,NOME VARCHAR(30)
      ,ENDERECO TIPO_ENDERECO
      ,SEXO TIPO_SEXO )

/*
Crie a tabela FUNCIONARIO, seguindo o modelo adiante:
Funcionario
• COD_FUNC TIPO_CODIGO chave primária,
• NOME VARCHAR(30)
• ENDERECO VARCHAR(80)
• SEXO TIPO_SEXO
*/
CREATE TABLE FUNCIONARIO
(
   COD_FUNC TIPO_CODIGO PRIMARY KEY
   ,NOME VARCHAR(30)
   ,ENDERECO VARCHAR(80)
   ,SEXO TIPO_SEXO
)

--Crie um sinônimo de nome TB_FUNCIONARIO para a tabela FUNCIONARIO.
CREATE SYNONYM TB_FUNCIONARIO FOR DBO.FUNCIONARIO

--Crie uma SEQUENCE de nome SQ_FUNCIONARIO, que inicie em 100 com incremento 2.
CREATE SEQUENCE SQ_FUNCIONARIO
START WITH 100
INCREMENT BY 2

/*
 Crie a tabela TB_FUNC_IDADE com os campos:
• Id_funcionario inteiro, auto numerável e chave primária
• Nome do funcionário alfanumérico com 50 caracteres
• Data de Nascimento Campo data
• Idade Campo calculado
CAST (FLOOR (CAST (GETDATE() - data_nascimento AS FLOAT) / 365.25) AS INT
*/
CREATE TABLE TB_FUNC_IDADE
(
   Id_funcionario INT IDENTITY(1,1) PRIMARY KEY
   ,FUNCIONARIO VARCHAR(50)
   ,Data_Nascimento DATETIME
   ,Idade AS CAST (FLOOR (CAST (GETDATE() - data_nascimento AS FLOAT) / 365.25) AS INT )

)

--Insira os dados da tabela de empregados para a tabela TB_FUNC_IDADE.
INSERT INTO TB_FUNC_IDADE
SELECT NOME, DATA_NASCIMENTO FROM TB_EMPREGADO

-- Consulte as informações e verifique o campo calculado.
SELECT * FROM TB_FUNC_IDADE