USE PEDIDOS

--Fazer uma query para calcular a média de preço de venda (PRECO_VENDA) da tabela TB_PRODUTO.
SELECT AVG(PRECO_VENDA) AS PRECO_MEDIO
FROM TB_PRODUTO

--Fazer uma query para calcular os totais vendidos por vendedor (mostrar TB_VENDEDOR.NOME e a soma de TB_PEDIDO.VLR_TOTAL) em janeiro de 2017. Exibir o nome do vendedor.
SELECT VEND.NOME
		,SUM(PED.VLR_TOTAL) AS TOT_VENDIDO
FROM TB_PEDIDO PED
INNER JOIN TB_VENDEDOR VEND
ON PED.CODVEN=VEND.CODVEN
WHERE PED.DATA_EMISSAO BETWEEN '2017.1.1' AND '2017.1.31'
GROUP BY VEND.NOME

--Fazer uma query para calcular o total comprado por cliente em janeiro de 2017. Exibir o nome do cliente.
SELECT CLI.CODCLI
		,CLI.NOME
		,SUM(PED.VLR_TOTAL) AS TOT_COMPRADO
FROM TB_PEDIDO PED
INNER JOIN TB_CLIENTE CLI
ON PED.CODCLI = CLI.CODCLI
WHERE PED.DATA_EMISSAO BETWEEN '2017.1.1' AND '2017.1.31'
GROUP BY CLI.CODCLI, CLI.NOME

--Fazer uma query para calcular os totais vendidos por vendedor em janeiro de 2018. Exibir o nome do vendedor e mostrar apenas os vendedores que venderam mais de R$40.000,00.
SELECT VEND.CODVEN
		,VEND.NOME
		,SUM(PED.VLR_TOTAL) AS TOT_VENDIDO
FROM TB_PEDIDO PED
INNER JOIN TB_VENDEDOR VEND
ON PED.CODVEN = VEND.CODVEN
WHERE PED.DATA_EMISSAO BETWEEN '2018.1.1' AND '2018.1.31'
GROUP BY VEND.CODVEN
       , VEND.NOME
HAVING SUM(PED.VLR_TOTAL) > 40000
ORDER BY 3

--Fazer uma query para calcular o total vendido de cada produto em janeiro de 2016. Exibir somente os 10 produtos que mais venderam.
SELECT TOP (10) PROD.ID_PRODUTO
			,PROD.DESCRICAO
			,SUM(ITEM.QUANTIDADE) AS QTD_TOTAL
			,SUM( ITEM.PR_UNITARIO * ITEM.QUANTIDADE ) AS VLR_TOTAL
FROM TB_ITENSPEDIDO ITEM
INNER JOIN TB_PRODUTO PROD
ON ITEM.ID_PRODUTO = PROD.ID_PRODUTO
INNER JOIN TB_PEDIDO PED
ON ITEM.NUM_PEDIDO = PED.NUM_PEDIDO
WHERE PED.DATA_EMISSAO BETWEEN '2016.1.1' AND '2016.1.31'
GROUP BY PROD.ID_PRODUTO
        ,PROD.DESCRICAO
ORDER BY 4 DESC
