--COLOCAR EM USO O BANCO DE DADOS SISTEMAS_PEDIDOS
USE SISTEMA_PEDIDOS

EXEC SP_HELP TB_EMPREGADO

--ADICIONAR A COLUNA CPF NA TABELA TB_EMPREGADO
ALTER TABLE TB_EMPREGADO
ADD CPF BIGINT NOT NULL

--CONSULTAR A TABELA TB_EMPREGADO
SELECT *
FROM TB_EMPREGADO