USE PEDIDOS

--LISTAR OS FUNCIONARIOS QUE POSSUEM SALARIO ENTRE 3000 E 5000
SELECT COD_DEPTO, NOME, SALARIO
FROM TB_EMPREGADO
WHERE SALARIO BETWEEN 3000 AND 5000
ORDER BY SALARIO 

SELECT COD_DEPTO, NOME, SALARIO
FROM TB_EMPREGADO
WHERE SALARIO >= 3000 AND SALARIO <= 5000
ORDER BY SALARIO 

SELECT *
FROM TB_PEDIDO

--FAZER UMA QUERY PARA LISTAR OS PEDIDOS ENTRE MIL E 3000
SELECT NUM_PEDIDO, CODCLI
FROM TB_PEDIDO
WHERE NUM_PEDIDO BETWEEN 1000 AND 3000
ORDER BY NUM_PEDIDO

--NOT BETWEEN
SELECT COD_DEPTO, NOME, SALARIO
FROM TB_EMPREGADO
WHERE SALARIO NOT BETWEEN 3000 AND 5000
ORDER BY SALARIO 