USE PEDIDOS

--COLUNA CALCULADA
--FAZER UMA QUERY PARA RETORNAR O NOME DO FUNCIONARIO E O SALARIO
--EXIBIR UMA COLUNA COM AUMENTO DE 10% NO SALARIO PARA CADA FUNCIONARIO
SELECT NOME, SALARIO,SALARIO *1.10 AS SALARIO_ATUAL
FROM TB_EMPREGADO

--CLAUSULA TOP
--FAZER UMA QUERY PARA LISTAR OS FUNCIONARIOS MAIS ANTIGOS
SELECT TOP (10) NOME, SALARIO, DATA_ADMISSAO
FROM TB_EMPREGADO
ORDER BY DATA_ADMISSAO

--FAZER UMA QUERY PARA LISTAR OS 10 EMPREGADOS MAIS NOVOS
--FAZER UMA QUERY PARA LISTAR OS FUNCIONARIOS MAIS ANTIGOS
SELECT TOP (10) NOME, SALARIO, DATA_ADMISSAO
FROM TB_EMPREGADO
ORDER BY DATA_ADMISSAO DESC

--CLAUSULA TOP WITH TIES
SELECT TOP (10) WITH TIES NOME, SALARIO
FROM TB_EMPREGADO
ORDER BY SALARIO DESC