USE SISTEMA_PEDIDOS
--CONSTRAINT CHECK NA COLUNA SINDICALIZADO
--S OU N
ALTER TABLE TB_EMPREGADO
ADD
CONSTRAINT CK_EMPREGADO_SIND CHECK(SINDICALIZADO IN ('S','N'))

EXEC SP_HELP TB_EMPREGADO

--CONSTRAINT DEFAULT
--COLUNA SINDICALIZADO RECEBERÁ POR PADRÃO 'S'
/*
SINTAXE DA CONSTRAINT DEFAULT
ALTER TABLE <NOME_TABELA>
ADD
CONSTRAINT <NOME_INTERNO_REGRA> DEFAULT('DADO') FOR <NOME_COLUNA>
*/
ALTER TABLE TB_EMPREGADO
ADD
CONSTRAINT DF_EMPREGADO_SIND DEFAULT('S') FOR SINDICALIZADO

