USE PEDIDOS

--SINTAXE DO SELECT
/*
SELECT <NOME_COLUNA> 
FROM <NOME_TABELA>
WHERE <CONDIÇÃO>
GROUP BY <NOME_COLUNAS>
HAVING <CONDIÇÃO>
ORDER BY <NOME_COLUNAS>
*/

--FAZER UMA QUERY PARA RETORNAR TODAS AS COLUNASS DA TABELA TB_EMPREGADO
SELECT *
FROM TB_EMPREGADO

--ESPECIFICAR O NOME DAS COLUNAS QUE QUEREMOS VISUALIZAR NA QUERY
--FAZER UMA QUERY PARA RETORNAR O NOME E SALARIO DA TB_EMPREGADO
SELECT NOME
		,SALARIO
FROM TB_EMPREGADO

--FAZER UMA QUERY PARA RETORNAR O NOME E SALARIO DA TB_EMPREGADO
--MAS O NOME DEVE VIR EM ORDEM CRESCENTE OU ASCENDENTE
SELECT NOME	
		,SALARIO
FROM TB_EMPREGADO
ORDER BY NOME ASC

--FAZER UMA QUERY PARA RETORNAR O NOME E SALARIO DA TB_EMPREGADO
--MAS O NOME DEVE VIR EM ORDEM DECRESCENTE OU DECESDENTE
SELECT NOME	
		,SALARIO
FROM TB_EMPREGADO
ORDER BY NOME DESC

