-- COLOCAR EM USO O BANCO DE DADOS SISTEMA_PEDIDOS
USE SISTEMA_PEDIDOS
--SINTAXE DO COMANDO PARA CRIAR TABELAS - CREATE TABLE <NOME_TABELA>
--(
-- DECLARAR OS CAMPOS E TIPOS DE DADOS
--)
--CRIAR A TABELA TB_DEPARTAMENTO
CREATE TABLE TB_DEPARTAMENTO
(COD_DEPTO INT PRIMARY KEY
,DEPTO VARCHAR(25) NOT NULL
)

--VERIFICAR A ESTRUTURA DA TABELA
EXEC SP_HELP TB_DEPARTAMENTO

--CONSULTAR OS REGISTROS DA TABELA TB_DEPARTAMENTO
--SELECT
/*
SELECT <CAMPOS>
FROM <NOME_TABELA>
*/

SELECT *
FROM TB_DEPARTAMENTO