--CRIAR O BANCO SISTEMA_PEDIDOS COM SCRIPT
CREATE DATABASE SISTEMA_PEDIDOS
ON
(NAME=SISTEMA_PEDIDOS
,FILENAME='C:\DADOS_DB\TABPEDIDOS.MDF'
,SIZE=10MB
,MAXSIZE=50MB
,FILEGROWTH=5MB
)
LOG ON
(
NAME=SISPEDIDO_LOG
,FILENAME='C:\DADOS_DB\SISPEDIDO_LOG.LDF'
,SIZE=2MB
,MAXSIZE=20MB
,FILEGROWTH=5MB
)

--COLOCAR O BANCO EM USO
USE SISTEMA_PEDIDOS
