USE PEDIDOS

CREATE TABLE CLIENTE_CTE
(
    COD_CLI INT,
    RAZAO_SOCIAL_CLI VARCHAR(50),
    NOME_FANTASIA_CLI VARCHAR(40),
    CNPJ_CLI VARCHAR(18),
    FONE CHAR(15)
)

-- ARMAZENAR OS DADOS DOS CLIENTES EM MEMORIA
WITH DADOS_CLIENTE (COD_CLI, RAZAO_SOCIAL_CLI, NOME_FANTASIA_CLI, CNPJ_CLI, FONE)
AS
(
    SELECT CODCLI,
           NOME,
           FANTASIA,
           CNPJ,
           FONE1
    FROM TB_CLIENTE
)
--SELECT * FROM DADOS_CLIENTE;

--TABELA CLIENTE_CTE RECEBE OS REGISTROS DA TABELA EM MEMORIA DADOS_CLIENTE
INSERT INTO CLIENTE_CTE(COD_CLI, RAZAO_SOCIAL_CLI, NOME_FANTASIA_CLI, CNPJ_CLI, FONE)
SELECT * 
FROM DADOS_CLIENTE

--CONSULTAR A TABELA CLIENTE_CTE
SELECT * 
FROM CLIENTE_CTE


