USE PEDIDOS

--DATEFROMPARTS
/*
SINTAXE
DATEFROMPARTS(ANO,MES,DIA)
*/
SELECT DATEFROMPARTS(2013,12,25) AS DATA
CREATE TABLE TESTEDATA
	(ANO INT
	,MES INT
	,DIA INT)

INSERT INTO TESTEDATA
VALUES(2023,11,10)
		,(2019,07,01)

SELECT ANO, MES, DIA
FROM TESTEDATA

SELECT DATEFROMPARTS(ANO, MES, DIA) AS DATA
FROM TESTEDATA

--HORA
--TIMEFROMPARTS
/*
SINTAXE
TIMEFROMPARTS(HORA, MINUTO, SEGUNDO, MILESSEGUNDOS, PRECISAO)
*/
SELECT TIMEFROMPARTS(10,25,15,0,0) AS HORA

--DATA E HORA
/*
SINTAXE
DATETIMEFROMPARTS(ANO, MES DIA, HORA, MINUTO, SEGUNDO, MILESSEGUNDO)
*/
SELECT DATETIMEFROMPARTS(2013,10,10,21,02,15,0) AS DATA_HORA

--DATETIMEFROMPARTS(ANO, MES DIA, HORA, MINUTO, SEGUNDO, MILESSEGUNDO,FRACAO, PRECISAO)
SELECT DATETIME2FROMPARTS(2013,10,02,21,10,15,0,0) AS DATA_HORA

--SMALLDATETIME(ANO, MES, DIA, HORA, MINUTO)
SELECT SMALLDATETIMEFROMPARTS(2023,12,14,21,40) AS DATA_HORA
