USE PEDIDOS

--OPERADORES DE CONJUNTOS
--EXCEPT
--QUAIS OS DEPARTAMENTOS QUE ESTAO CADASTRADOS NA TABELA DEPARTAMENTO E NÃO ESTAO SENDO ASSOCIADOS NA TABELA DE EMPREGADO
SELECT *
FROM TB_EMPREGADO
ORDER BY COD_DEPTO

SELECT COD_DEPTO
FROM TB_DEPARTAMENTO
EXCEPT
SELECT COD_DEPTO
FROM TB_EMPREGADO

--CRIAR TABELAS DADOS_EMP COM COD_DEPTO E DEPTO 
SELECT EMP.COD_DEPTO,DEPTO.DEPTO
INTO DADOS_EMP
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON DEPTO.COD_DEPTO=EMP.COD_DEPTO

SELECT COD_DEPTO,DEPTO
FROM TB_DEPARTAMENTO
EXCEPT
SELECT COD_DEPTO,DEPTO
FROM DADOS_EMP
