USE PEDIDOS

--GROUP BY
--WITH ROLLUP
--FAZER UMA QUERY PARA EXIBIR O TOTAL DA QUANTIDADE DE PRODUTO COMPRADA POR CLIENTE E O VENDEDOR QUE ATENDEU ESTE CLIENTE

SELECT VEND.NOME AS NOME_VENDEDOR
		,CLI.NOME AS NOME_CLIENTE
		,TIPO.TIPO AS TIPO_PRODUTO
		,SUM(ITEM.QUANTIDADE) AS TOTAL_QTDPRODUTO
FROM TB_PEDIDO AS PED
INNER JOIN TB_CLIENTE AS CLI
ON PED.CODCLI=CLI.CODCLI
INNER JOIN TB_VENDEDOR AS VEND
ON PED.CODVEN=VEND.CODVEN
INNER JOIN TB_ITENSPEDIDO AS ITEM
ON ITEM.NUM_PEDIDO=PED.NUM_PEDIDO
INNER JOIN TB_PRODUTO AS PROD
ON ITEM.ID_PRODUTO=PROD.ID_PRODUTO
INNER JOIN TB_TIPOPRODUTO AS TIPO
ON PROD.COD_TIPO=TIPO.COD_TIPO
GROUP BY VEND.NOME, CLI.NOME, TIPO.TIPO
WITH ROLLUP
