USE PEDIDOS

--FUNÇOES PARA DATA
--RETORNAR A DATA E HORA ATUAL DO SERVIDOR
SELECT GETDATE() AS DATA_HORA_ATUAL

--RETORNAR SOMENTE O DIA
SELECT DAY(GETDATE()) AS DIA_ATUAL

--RETORNAR O DIA EM NUMERO
SELECT DAY('2023/12/09') AS DIA

--RETORNAR O MES EM NUMERO
SELECT MONTH(GETDATE()) AS MES_ATUAL
SELECT MONTH('1950/07/10') AS MES

--RETORNAR O ANO EM NUMERO
SELECT YEAR(GETDATE()) AS ANO_ATUAL
SELECT YEAR('1950/07/10') AS ANO

--RETORNAR O NOME DO FUNCIONARIO, O DIA, O MES E O ANO DA DATA_NASCIMENTO
SELECT NOME
		,DATA_NASCIMENTO
		,DAY(DATA_NASCIMENTO) AS DIA
		,MONTH(DATA_NASCIMENTO) AS MES
		,YEAR(DATA_NASCIMENTO) AS ANO
FROM TB_EMPREGADO

--DATENAME
SELECT NOME
		,DATA_NASCIMENTO
		,DAY(DATA_NASCIMENTO) AS DIA
		,MONTH(DATA_NASCIMENTO) AS MES
		,DATENAME(MONTH, DATA_NASCIMENTO) AS MES_EXTENSO
		,YEAR(DATA_NASCIMENTO) AS ANO
FROM TB_EMPREGADO
