USE PEDIDOS

--FUNÇOES MATEMÁTICAS
--FLOOR
/*
SINTAXE
FLOOR(VALOR)
*/
SELECT FLOOR(1.3012) AS VALOR_INTEIRO

SELECT ID_PRODUTO
		,DESCRICAO
		,PRECO_CUSTO
		,FLOOR(PRECO_CUSTO) AS VALOR_INTEIRO
FROM TB_PRODUTO

--FUNÇAO PI()
SELECT PI() AS VALOR_DE_PI

--RAND() -- VALOR RANDOMICO - ALEATORIO
SELECT RAND() AS VALOR_RANDOMICO

--ROUND - ARREDONDAMENTO
SELECT ID_PRODUTO
		,DESCRICAO
		,PRECO_VENDA
		,ROUND(PRECO_VENDA,2) AS PRECO_ARREDONDADO
FROM TB_PRODUTO

--EXIBIR SOMENTE 2 CASAS DECIMAIS NA COLUNA QUE OCORREU O ARREDONDAMENTO
SELECT ID_PRODUTO
		,DESCRICAO
		,PRECO_VENDA
		,FORMAT(ROUND(PRECO_VENDA,2),'#########0.00') AS PRECO_ARREDONDADO
FROM TB_PRODUTO

/*
SINTAXE FORMAT
FORMAT(FORMATO_DESEJADO)
#RETORNA NUMERO
. RETORNA AS CASAS DECIMAIS
0 RETORNA O NUMERO ZERO E QUANTIDADE DE CASAS DECIMAIS APOS O PONTO(.)
*/

EXEC SP_HELP TB_PRODUTO

