USE PEDIDOS

--CONCATENAR
-- + E COM A FUNÇÃO CONCAT
--FAZER UMA QUERY PARA RETORNAR O NOME, ENDEREÇO E O CEP DO CLIENTE
--EXIBIR O ENDEREÇO E O CEP NA MESMA COLUNA
SELECT NOME
		,ENDERECO+' & '+ CEP AS ENDEREÇO
FROM TB_CLIENTE

--FUNÇAO CONCAT
SELECT NOME
		,CONCAT(ENDERECO,' & ', CEP) AS ENDEREÇO
FROM TB_CLIENTE


--LOWER(LETRA MINUSCULA)/UPPER(LETRA MAIUSCULA)
SELECT NOME
		,LOWER(NOME) AS NOME_MINUSCULO
FROM TB_CLIENTE

SELECT UPPER('teste de letra minuscula para maiuscula') AS LETRA

