USE PEDIDOS

--CUSTO POR DEPARTAMENTO
SELECT EMP.COD_DEPTO
		,DEPTO.DEPTO
		,SUM(EMP.SALARIO) AS TOTAL_SALARIAL
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
GROUP BY EMP.COD_DEPTO, DEPTO

--HAVING
--VISUALIZAR OS DEPARTAMENTOS COM CUSTO MAIOR QUE 18000
SELECT EMP.COD_DEPTO
		,DEPTO.DEPTO
		,SUM(EMP.SALARIO) AS TOTAL_SALARIAL
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
GROUP BY EMP.COD_DEPTO, DEPTO
HAVING SUM(SALARIO) >18000

--EXIBIR A MEDIA SALARIAL POR DEPARTAMENTO
SELECT EMP.COD_DEPTO
		,DEPTO.DEPTO
		,AVG(EMP.SALARIO) AS TOTAL_SALARIAL
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
GROUP BY EMP.COD_DEPTO, DEPTO

--EXIBIR A MEDIA SALARIAL POR DEPARTAMENTO E EXIBIR SOMENTE A MEDIA MAIOR QUE 2000
SELECT EMP.COD_DEPTO
		,DEPTO.DEPTO
		,AVG(EMP.SALARIO) AS MEDIA_SALARIAL
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
GROUP BY EMP.COD_DEPTO, DEPTO
HAVING AVG(SALARIO) >2000
ORDER BY MEDIA_SALARIAL
