USE SISTEMA_PEDIDOS

SELECT *
FROM TB_DEPENDENTE

SET IDENTITY_INSERT TB_DEPENDENTE ON

--INSERIR O CODIGO COD_DEPENDENTE=3 PARA O DEPENDENTE ALBERTO
INSERT INTO TB_DEPENDENTE(COD_DEPENDENTE,CODFUN,NOME, DATA_NASCIMENTO)
VALUES(3,3,'ALBERTO','1990/07/20')

SELECT *
FROM TB_DEPENDENTE

select * 
from TB_EMPREGADO

INSERT INTO TB_DEPENDENTE(COD_DEPENDENTE,CODFUN,NOME, DATA_NASCIMENTO)
VALUES(5,2,'MARTA','1990/07/20')

SET IDENTITY_INSERT TB_DEPENDENTE OFF

INSERT INTO TB_DEPENDENTE(CODFUN,NOME, DATA_NASCIMENTO)
VALUES(2,'PEDRO','1992/01/02')


SELECT *
FROM TB_DEPENDENTE

SELECT *
FROM TB_DEPENDENTE