USE SISTEMA_PEDIDOS

--RETORNAR O NOME DO FUNCIONARIO, O NOME DO DEPARTAMENTO
--ONDE O NOME DOS FUNCIONARIOS INICIAM COM A LETRA 'O'
SELECT NOME AS NOME_FUNCIONARIO	
		,DEPTO AS DEPARTAMENTO
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
WHERE NOME LIKE 'O%'

--COLOCAR EM USO O BANCO DE DADOS PEDIDOS
USE PEDIDOS

--CLAUSULA WHERE
SELECT NOME AS NOME_FUNCIONARIO	
		,DEPTO AS DEPARTAMENTO
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
WHERE NOME LIKE 'O%'

--ORDER BY
SELECT NOME AS NOME_FUNCIONARIO	
		,DEPTO AS DEPARTAMENTO
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
ORDER BY NOME DESC

--RETORNAR O NOME DO FUNCIONARIO, O NOME DO DEPARTAMENTO,O NOME DO CARGO E SALARIO
SELECT NOME
		,DEPTO AS NOME_DEPARTAMENTO
		,CARGO AS NOME_CARGO
		,SALARIO
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
INNER JOIN TB_CARGO AS CARGO
ON EMP.COD_CARGO=CARGO.COD_CARGO

--FILTRAR OS DEPARTAMENTOS COMPRAS E PRODUÇÃO
SELECT NOME
		,DEPTO AS NOME_DEPARTAMENTO
		,CARGO AS NOME_CARGO
		,SALARIO
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
INNER JOIN TB_CARGO AS CARGO
ON EMP.COD_CARGO=CARGO.COD_CARGO
WHERE DEPTO IN('COMPRAS','PRODUCAO')



