USE SISTEMA_PEDIDOS

SELECT *
FROM TB_EMPREGADO

--FAZER UMA QUERY PARA RETORNAR O NOME DO FUNCIONARIO, O NOME DO CARGO QUE EXERCE E O SALARIO
SELECT NOME
		,SALARIO
		,CARGO
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_CARGO AS CARGO
ON EMP.COD_CARGO=CARGO.COD_CARGO

--COLOCAR EM USO O BANCO DE DADOS PEDIDOS
USE PEDIDOS

SELECT * 
FROM TB_EMPREGADO

--RETORNAR O NOME DO FUNCIONARIO, A DESCRIÇAO DO DEPARTAMENTO E O SALARIO
SELECT NOME
		,DEPTO,SALARIO
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO

SELECT * 
FROM TB_DEPARTAMENTO


