USE SISTEMA_PEDIDOS

--FAZER UMA QUERY(CONSULTA) NA TABELA TB_EMPREGADO
SELECT *
FROM TB_EMPREGADO

ALTER TABLE TB_EMPREGADO
ADD COD_SUPERVISOR INT NULL;


--POPULAR A TB_EMPREGRADO
--INSERT DECLARATIVO
INSERT INTO TB_EMPREGADO (CODFUN, NOME, NUM_DEPEND
						,DATA_NASCIMENTO, COD_DEPTO
						,COD_CARGO,DATA_ADMISSAO, SALARIO
						,PREMIO_MENSAL, SINDICALIZADO
						,OBS, FOTO, COD_SUPERVISOR, CPF)
VALUES(1,'OLAVO TRINDADE',4
	  ,'1950/10/05'
	  ,4
	  ,2
	  ,'1986/06/06'
	  ,3000
	  ,1200
	  ,'S'
	  ,'N/A'
	  ,'N/A'
	  ,NULL
	  ,14588876544)

EXEC SP_HELP TB_EMPREGADO

SELECT * 
FROM TB_DEPARTAMENTO
