USE SISTEMA_PEDIDOS

--POPULAR A TABELA TB_CARGO COM INSTERT POSICIONAL
--CONSULTA
SELECT *
FROM TB_CARGO

--INSERT POSICIONAL
/*
SINTAXE
INSERT INTO TB_CARGO
VALUES(DECLARAR AS INFORMAÇÕES DE CADA COLUNA RESPEITANDO A ORDEM DE CRIAÇÃO NA TABELA)
*/
INSERT INTO TB_CARGO
VALUES(1,'SUPERVISORA COMERCIAL',8300)

SELECT *
FROM TB_CARGO

--INSERIR MAIS DE UM REGISTRO NA TABELA
INSERT INTO TB_CARGO
VALUES(2,'QUALIDADE',2400)
	,(3,'DIRETOR',12000)
	,(4,'COMPRADOR',800)

