--COLOCAR EM USO O BANCO DE DADOS PEDIDOS
USE PEDIDOS

SELECT * 
FROM TB_CARGO

--COLOCAR EM USO O BANCO SISTEMA_PEDIDOS
USE SISTEMA_PEDIDOS
SELECT * 
FROM TB_CARGO

--INSERIR OS REGISTROS DA TABELA TB_CARGO QUE ESTA NO BANCO DE DADOS PEDIDOS
INSERT INTO TB_CARGO(COD_CARGO,CARGO,SALARIO_INIC)
SELECT COD_CARGO, CARGO, SALARIO_INIC
FROM PEDIDOS..TB_CARGO
WHERE COD_CARGO > 6

SELECT * 
FROM TB_CARGO

--CRIAR UMA TABELA COM O NOME TB_CLIENTE
CREATE TABLE TB_CLIENTE
(CODCLI INT PRIMARY KEY
,NOME CHAR(50)
,ESTADO CHAR(2)
)

SELECT * 
FROM TB_CLIENTE

--CLAUSULA TOP
--INSERIR 10 REGISTROS DA TABELA TB_CLIENTE DO BANCO DE DADOS PEDIDOS
--NA TABELA TB_CLIENTE DO BANCO DE DADOS SISTEMAS_PEDIDOS
INSERT TOP(10) INTO TB_CLIENTE(CODCLI, NOME, ESTADO)
SELECT CODCLI, NOME, ESTADO
FROM PEDIDOS..TB_CLIENTE

SELECT * 
FROM TB_CLIENTE

SELECT * 
FROM PEDIDOS..TB_CLIENTE

--INSERIR REGISTROS DO ESTADO DE 'SC' NA TABELA TB_CLIENTE
INSERT INTO TB_CLIENTE(CODCLI, NOME, ESTADO)
SELECT CODCLI, NOME, ESTADO
FROM PEDIDOS..TB_CLIENTE
WHERE ESTADO='SC'

SELECT  * 
FROM TB_CLIENTE

--SINTAXE DO INSERT SELECT
/*
INSERT INTO <NOME_TABELA>(COLUNAS)
SELECT (COLUNAS)
FROM <NOME_BANCO_DADOS>..<NOME_TABELA>
WHERE <CONDIÇÃO>
*/

