USE PEDIDOS 
--LISTA: IN/NOT IN
--FAZER UMA QUERY PARA EXIBIR OS FUNCIONARIOS DOS DEPARTAMENTOS 1,3,4 OU 7
SELECT NOME, COD_DEPTO
FROM TB_EMPREGADO
WHERE COD_DEPTO =1
OR COD_DEPTO=3
OR COD_DEPTO=4
OR COD_DEPTO =7
ORDER BY COD_DEPTO

--IN
SELECT NOME, COD_DEPTO
FROM TB_EMPREGADO
WHERE COD_DEPTO IN(1,3,4,7)
ORDER BY COD_DEPTO

--EXIBIR OS CLIENTES DOS ESTADOS: AM,PR,RJ E SP
SELECT NOME, ESTADO
FROM TB_CLIENTE
WHERE ESTADO IN('AM','PR','RJ','SP')
ORDER BY ESTADO

--EXIBIR OS CLIENTES DE TODOS OS ESTADOS EXCLUINDO OS ESTADOS: AM, PR, RJ, SP
SELECT NOME, ESTADO
FROM TB_CLIENTE
WHERE ESTADO NOT IN('AM','PR','RJ','SP')
ORDER BY ESTADO

