use pedidos

--FUNÇÃO NULLIF
/*
REALIZA UMA ANALISE ENTRE DOIS VALORES OU COLUNAS EM UMA QUERY E COMO RESULTADO TEM-SE:
SE OS DOIS VALORES OU COLUNAS SAO IGUAIS ENTAO
	RETORNARÁ NULL
SE OS DOIS VALORES OU COLUNAS FOREM DIFERENTES ENTAO
	RETORNARÁ O PRIMEIRO VALOR OU PRIMEIRA COLUNA
*/
SELECT NULLIF(7,7) AS IGUAIS, NULLIF(55,4) AS DIFERENTES

SELECT NOME	
		,ESTADO
		,EST_COB
		,NULLIF(ESTADO, EST_COB) AS ESTADO_ANALISE
FROM TB_CLIENTE
ORDER BY ESTADO

--FUNÇÃO COALESCE
SELECT NOME	
		,ESTADO
		,EST_COB
		,COALESCE(ESTADO, EST_COB) AS ESTADO_ANALISE
FROM TB_CLIENTE
ORDER BY ESTADO

SELECT NOME	
		,EST_COB
		,ESTADO
		,COALESCE(EST_COB,ESTADO) AS ESTADO_ANALISE
FROM TB_CLIENTE
ORDER BY EST_COB
