USE PEDIDOS

SELECT *
FROM TB_EMPREGADO
ORDER BY NOME

--EXIBIR OS FUNCIONARIOS COM O NOME INICIANDO COM 'C'
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE 'C%'

--EXIBIR OS FUNCIONARIOS ONDE O NOME INCIA COM 'MARIA'
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE 'MARIA%'

--EXIBIR OS FUNCIONARIOS ONDE O NOME INCIA COM 'MA'
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE 'MA%'

--EXIBIR OS FUNCIONARIOS ONDE O NOME INCIA COM 'M'
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE 'M%'

--EXIBIR OS FUNCIONARIOS ONDE O NOME INCIA COM 'P'
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE 'P%'

--EXIBIR OS FUNCIONARIOS ONDE O NOME INCIA COM 'PE'
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE 'PE%'

--EXIBIR NOMES DE FUNCIONARIOS QUE TERMINAM COM 'SILVA'
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE '%SILVA'

--EXIBIR NOMES DE FUNCIONARIOS QUE TERMINAM COM 'ZA'
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE '%ZA'

--EXIBIR NOMES DE FUNCIONARIOS QUE CONTENHAM A PALAVRA MARIA NO NOME
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE '%MARIA%'