USE PEDIDOS

--OPERADOR LIKE
--EXIBIR NOME DE FUNCIONARIO INICIANDO COM 'JOSE' OU 'JOSÉ'
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE 'JOSE%' 
OR NOME LIKE 'JOSÉ%'

SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE 'JOS[EÉ]%' 

--NOME DO FUNCIONARIO QUE CONTEM SOUSA OU SOUZA
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE '%SOU[SZ]A%' 

--NÃO CONHECEMOS A PRIMEIRA LETRA E A SEGUNDA LETRA CONHECEMOS:'U'
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE '_U%'

--NÃO CONHECEMOS A PRIMEIRA LETRA E A SEGUNDA LETRA CONHECEMOS:'U'OU 'Ú'
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE '_[UÚ]%'

--CONHECEMOS A PRIMEIRA LETRA 'L' E NÃO CONHECEMOS 4 LETRAS'
SELECT NOME
FROM TB_EMPREGADO
WHERE NOME LIKE 'L____%'
