USE PEDIDOS

--MERGE

--CRIAR UMA COPIA DA TABELA DE EMPREGADO COM O NOME EMP_PROD
SELECT *
INTO EMP_PROD
FROM TB_EMPREGADO

SELECT * FROM TB_EMPREGADO

SELECT * FROM EMP_PROD

--APAGAR OS REGISTROS DE COD_CARGO = 3
DELETE FROM EMP_PROD
WHERE COD_CARGO = 3

--ATUALIZAR OS REGISTROS AUMENTANDO O SALARIO DO FUNCIONARIO EM 10% PARA OS FUNCIONARIOS DO DEPARTAMENTO 2
UPDATE EMP_PROD
SET SALARIO = SALARIO * 1.10
WHERE COD_DEPTO = 2

