USE PEDIDOS

--INTRODUÇAAO A PROCEDURE
--CRIAR UMA PROCEDURE
CREATE PROCEDURE SP_RELATORIO_PROD
AS 
BEGIN
	SELECT * 
	FROM TB_PRODUTO
	WHERE ID_PRODUTO = 77
END

--EXECUTAR A PROCEDURE
EXECUTE SP_RELATORIO_PROD
--OU
EXEC SP_RELATORIO_PROD

--VISUALIZAR O SCRIPT DA PROCEDURE
EXEC SP_HELPTEXT SP_RELATORIO_PROD
