USE PEDIDOS

SELECT *
FROM EMPREGADO_TEMP

--VISUALIZAR A ESTRUTURA DA TABELA
EXEC sp_help EMPREGADO_TEMP

--RENOMEAR A COLUNA DE UMA TABELA
--0BS PARA OBSERVACAO
--SP_RENAME
--SINTAXE -> EXEC SP_RENAME 'NOME_TABELA.COLUNA','NOMEATUALCOLUNA'
EXEC sp_rename 'EMPREGADO_TEMP.OBS','OBSERVACAO'

--RENOMEAR A TABELA EMPREGADO_TEMP PARA EMP_TEMPORARIA
EXEC SP_RENAME 'DBO.EMPREGADO_TEMP','EMP_TEMPORARIA'

SELECT *
FROM EMP_TEMPORARIA

