USE PEDIDOS
--RIGHT JOIN
--RETORNAR OS DEPARTAMENTOS QUE ESTÃO CADASTRADOS NA TB_DEPARTAMENTO MAS NAO FORAM ASSOCIADOS TB_EMPREGADO
SELECT NOME
		,DEPTO
		,SALARIO
FROM TB_EMPREGADO AS EMP RIGHT JOIN TB_DEPARTAMENTO AS DEPTO
ON EMP.COD_DEPTO=DEPTO.COD_DEPTO
ORDER BY SALARIO

SELECT NOME
		,CARGO
		,SALARIO
FROM TB_EMPREGADO AS EMP RIGHT JOIN TB_CARGO AS CARGO
ON EMP.COD_CARGO=CARGO.COD_CARGO
ORDER BY SALARIO

