USE PEDIDOS

--SELF JOIN - AUTORRELACCIONAMENTO
SELECT CODFUN
		,NOME
		,COD_SUPERVISOR
FROM TB_EMPREGADO

/*
OLAVO - LUCIO MITSUI
JOSE REIS - SEBASTIAO SILVA
MARCELO SOARES - ANA MARIA OLIVEIRA
*/

--FAZER UMA QUERY NA TB_EMPREGADO PARA RETORNAR O NOME DO FUNCIONARIO E O NOME DO SUPERVISOR DESTE FUNCIONARIO
SELECT EMP.NOME AS NOME_FUNCIONARIO
		,SUPERIOR.NOME AS NOME_SUPERIOR
FROM TB_EMPREGADO AS EMP
INNER JOIN TB_EMPREGADO AS SUPERIOR
ON EMP.COD_SUPERVISOR=SUPERIOR.CODFUN
