USE PEDIDOS

CREATE TABLE CAD_FUNCIONARIO
(
ID INT
,NOME VARCHAR(20)
,SEXO CHAR (1)
,DATA_NASCIMENTO DATETIME
)

--CRIAR UM SIN0NIMO - SYNONYM
CREATE SYNONYM TAB_EMPREGADO FOR DBO.CAD_FUNCIONARIO

--TABELA COM SINONIMO
SELECT *
FROM TAB_EMPREGADO
--TABELA COM O NOME OFICIAL
SELECT *
FROM CAD_FUNCIONARIO

INSERT INTO CAD_FUNCIONARIO
VALUES (1,'MARIO QUINTANA','M','1945/03/02')

--COLUNAS COMPUTADAS
SELECT * 
FROM TB_EMPREGADO

--CALCCULO DE IDADE EM NUMEROS
SELECT NOME
		,DATA_NASCIMENTO
		,FLOOR(CAST(GETDATE()-DATA_NASCIMENTO AS FLOAT)/365.25) AS IDADE
FROM TB_EMPREGADO

--ACRESCENTAR A COLUNA IDADE COM A FORMULA QUE CALCULA A IDADE
ALTER TABLE TB_EMPREGADO
ADD IDADE
AS FLOOR(CAST(GETDATE()-DATA_NASCIMENTO AS FLOAT)/365.25)

SELECT NOME
		,DATA_NASCIMENTO
		,IDADE
FROM TB_EMPREGADO

--INSERIR UM REGISTRO NA TABELA TB_EMPREGADO
INSERT INTO TB_EMPREGADO (NOME, SALARIO,DATA_NASCIMENTO)
VALUES ('MARIA ANTONIA SILVA', 2500,'1974/11/04')

SELECT NOME
		,DATA_NASCIMENTO
		,IDADE
FROM TB_EMPREGADO