USE PEDIDOS

--LISTAR O NOME DO FUNCIONARIO, SALARIO E O SALARIO INCIAL QUE ESTA CADASTRADO TB_CARGO
SELECT CODFUN
		, NOME
		,COD_CARGO
		,SALARIO
		,(SELECT SALARIO_INIC
		FROM TB_CARGO
		WHERE COD_CARGO= TB_EMPREGADO.COD_CARGO) AS SALARIO_INICIAL
FROM TB_EMPREGADO

--OU
SELECT CODFUN
		, NOME
		,COD_CARGO
		,SALARIO
		,(SELECT SALARIO_INIC
		FROM TB_CARGO
		WHERE COD_CARGO= EMP.COD_CARGO) AS SALARIO_INICIAL
FROM TB_EMPREGADO AS EMP

--EXIBIR O TOTAL VENDIDO POR VENDEDOR NO PERIODO DE JANEIRO DE 2016 E REALIZAR O CALCULO DE TOTAL DO PEDIDO EM RELAÇAO AO TOTAL DE VENDAS
SELECT  PED.CODVEN
		,VEND.NOME AS NOME_VENDEDOR
		,SUM(PED.VLR_TOTAL) AS TOTAL
		,(SELECT SUM(VLR_TOTAL)
		FROM TB_PEDIDO
		WHERE DATA_EMISSAO BETWEEN '2016/01/01' AND '2016/01/31')/SUM(PED.VLR_TOTAL) AS PERCENTUAL
FROM TB_PEDIDO AS PED
INNER JOIN TB_VENDEDOR AS VEND
ON PED.CODVEN=VEND.CODVEN
WHERE YEAR(PED.DATA_EMISSAO) = 2016
GROUP BY PED.CODVEN, VEND.NOME
