USE PEDIDOS

--SUBQUERY
--MEDIA SALARIAL DA TABELA TB_EMPREGADO
SELECT AVG(SALARIO) AS MEDIA_SALARIAL
FROM TB_EMPREGADO
--2360.689655

--FAZER UMA QUERY PARA RETORNAR O NOME DOS FUNCIONARIOS QUE GANHAM MAIS QUE A MEDIA SALARIAL DA BASE DE EMPREGADOS
SELECT NOME	
		,SALARIO
FROM TB_EMPREGADO
WHERE SALARIO > (SELECT AVG(SALARIO)
				FROM TB_EMPREGADO)

--EXIBIR O NOME DOS FUNCIONARIOS QUE GANHAM MAIS QUE O MENOR SALARIO ENCONTRADO NA TB_EMPREGADO
SELECT NOME	
		,SALARIO
FROM TB_EMPREGADO
WHERE SALARIO = (SELECT MIN(SALARIO)
				FROM TB_EMPREGADO)

--EXIBIR O NOME DOS FUNCIONARIOS QUE GANHAM IGUAL AO MAIOR SALARIO ENCONTRADO NA TB_EMPREGADO
SELECT NOME	
		,SALARIO
FROM TB_EMPREGADO
WHERE SALARIO = (SELECT MAX(SALARIO)
				FROM TB_EMPREGADO)
