USE PEDIDOS

--EXIBIR O NUMERO DO PEDIDO, A DATA_EMISSAO, VLR_TOTAL DO PEDIDO
-- MAS TRAZER SOMENTE OS REGISTROS DO ANO DE 2016
SELECT *
FROM (SELECT NUM_PEDIDO
		,DATA_EMISSAO
		,VLR_TOTAL
		FROM TB_PEDIDO
		WHERE YEAR(DATA_EMISSAO) = 2016) AS TABELA_VENDAS_2016
WHERE TABELA_VENDAS_2016.VLR_TOTAL > 5000
ORDER BY VLR_TOTAL

SELECT *
FROM (SELECT NUM_PEDIDO
		,DATA_EMISSAO
		,VLR_TOTAL
		FROM TB_PEDIDO
		WHERE YEAR(DATA_EMISSAO) = 2016) AS TABELA_VENDAS_2016
WHERE VLR_TOTAL > 5000
ORDER BY VLR_TOTAL
