USE SISTEMA_PEDIDOS

SELECT * 
FROM TB_EMPREGADO

INSERT INTO TB_EMPREGADO(CODFUN, NOME, NUM_DEPEND
						,DATA_NASCIMENTO,COD_DEPTO
						,COD_CARGO,DATA_ADMISSAO,SALARIO
						,PREMIO_MENSAL,SINDICALIZADO
						,OBS, FOTO, COD_SUPERVISOR, CPF)
VALUES(2, 'JOSE REIS',6
			,'1952/10/09'
			,2
			,5
			,'1987/05/02'
			,600
			,1250
			,'S'
			,'N/A'
			,'N/A'
			,2
			,34523343454)
INSERT INTO TB_EMPREGADO(CODFUN, NOME, NUM_DEPEND
						,DATA_NASCIMENTO,COD_DEPTO
						,COD_CARGO,DATA_ADMISSAO,SALARIO
						,PREMIO_MENSAL,SINDICALIZADO
						,OBS, FOTO, COD_SUPERVISOR, CPF)
VALUES(3,'MARCELO SOARES',1
		,'1950/06/06'
		,5
		,2
		,'1986/10/05'
		,2400
		,1200
		,'S'
		,'N/A'
		,'N/A'
		,2
		,14513348934)

SELECT * 
FROM TB_EMPREGADO

--TESTE DA CONSTRAINT UNIQUE(CPF)
--VISUALIZAR A ESTRUTURA DATABELA TB_EMPREGADO
EXEC SP_HELP TB_EMPREGADO

INSERT INTO TB_EMPREGADO(CODFUN, NOME, NUM_DEPEND
						,DATA_NASCIMENTO,COD_DEPTO
						,COD_CARGO,DATA_ADMISSAO,SALARIO
						,PREMIO_MENSAL,SINDICALIZADO
						,OBS, FOTO, COD_SUPERVISOR, CPF)
VALUES(4, 'PAULO CEESAR JUNIOR',2
		,'1952/03/19',5,2
		,'1987/05/06',600,1250,'S'
		,'N/A','N/A',1,20714548900)

SELECT * 
FROM TB_EMPREGADO


