USE PEDIDOS 

--USER DEFINED DATATYPE - TIPO DE DADOS DEFINIDO PELO USUARIO

--CRIAR UM TIPO DE DADOS PARA A COLUNA ENDEREÇO E QUANTIDADE DE CARACTERES IGUAL A (60)
CREATE TYPE TIPO_ENDERECO
FROM VARCHAR (60) NOT NULL

--VERIFICAR OS TIPO DE DADOS DEFINIDOS PELO USUARIO CRIADOS
SELECT *
FROM SYSTYPES
WHERE UID = 1

--CRIAR OS TIPO DE DADOS
/*
TIPO_NOME_PESSOA VARCHAR(40)NOT NULL
TIPO_PRECO NUMERIC(12,2) NOT NULL
TIPO_SN CHAR(1) NULL
*/

USE MASTER
CREATE DATABASE DB_USERDATATYPE
USE DB_USERDATATYPE


CREATE TYPE TIPO_NOME_PESSOA
FROM VARCHAR(40) NOT NULL

CREATE TYPE TIPO_PRECO
FROM NUMERIC(12,2) NOT NULL

CREATE TYPE TIPO_SN
FROM CHAR(1) NULL

--CRIAR UMA TABELA PRODUTOS
CREATE TABLE PRODUTOS
(COD_PROD INT IDENTITY(1,1)
,DESCRICAO VARCHAR(80)
,PRECO_VENDA TIPO_PRECO
,SN_ATIVO TIPO_SN
,CONSTRAINT PK_PRODUTO_COD PRIMARY KEY(COD_PROD))

SELECT * 
FROM PRODUTOS
