USE PEDIDOS

--UNION (CONTEM DISTINC POR DEFAULT/ELIMINA DUPLICIDADE) / UNION ALL(não elimina a duplicidade)
--UNIR OS DADOS DE DUAS TABELAS
SELECT NOME
FROM TB_EMPREGADO
UNION
SELECT NOME
FROM TB_VENDEDOR

SELECT NOME
FROM TB_EMPREGADO
UNION ALL
SELECT NOME
FROM TB_MAIOR_SALARIO
ORDER BY NOME
