USE PEDIDOS

--UPDATE PARA MAIS DE UMA COLUNA
SELECT *
FROM TB_CLIENTE
ORDER BY ENDERECO

--CRIAR UMA COPIA DA TABELA TB_CLIENTE COMO CLIENTE_TEMP
SELECT * 
INTO CLIENTE_TEMP
FROM TB_CLIENTE

SELECT *
FROM CLIENTE_TEMP
WHERE CODCLI=391

--ATUALIZAR OS CAMPOS ENDEREÇO, BAIRRO, CIDADE, ESTADO E CEP DO CLIENTE DE CODIGO 391
UPDATE CLIENTE_TEMP
SET ENDERECO = 'AV.PAULISTA, 1902'
	,BAIRRO = 'BELA VISTA'
	,CIDADE = 'SÃO PAULO'
	,ESTADO = 'SP'
	,CEP = '01311100'
WHERE CODCLI = 391

SELECT *
FROM CLIENTE_TEMP
WHERE CODCLI=391

SELECT *
FROM CLIENTE_TEMP
ORDER BY ENDERECO

--ATUALIZAR O ENDEREÇO, BAIRRO, CIDADE, ESTADO E CCEP DO CLIENTE DE CODIGO = 430
UPDATE CLIENTE_TEMP
SET ENDERECO = 'AV.DAS PALMEIRAS, 55'
	,BAIRRO = 'VILA DAS PALMEIRAS'
	,CIDADE = 'SÃO PAULO'
	,ESTADO = 'SP'
	,CEP = '02504000'
WHERE CODCLI = 430

SELECT *
FROM CLIENTE_TEMP
WHERE CODCLI=430
