USE PEDIDOS

--CRIAR UMA COPIA DA TABELA TB_EMPREGADO COM O NOME EMPREGADO_TEMP
SELECT *
INTO EMPREGADO_TEMP
FROM TB_EMPREGADO

--EMPREGADO_TEMP
--UPDATE - ATUALIZAÇÕES
SELECT *
FROM EMPREGADO_TEMP

--ATUALIZAR EM 20% O SALARIO DOS FUNCIONARIOS QUE PERTENCEM AO DEPARTAMENTO 2
SELECT *
FROM EMPREGADO_TEMP 
WHERE COD_DEPTO =2

UPDATE EMPREGADO_TEMP
SET SALARIO = SALARIO * 1.2
WHERE COD_DEPTO = 2

--APAGAR A TABELA EMPREGADO_TEMP
DROP TABLE EMPREGADO_TEMP

SELECT *
INTO EMPREGADO_TEMP
FROM TB_EMPREGADO

SELECT *
FROM EMPREGADO_TEMP 
WHERE COD_DEPTO =2

--ABRIR UMA TRANSAÇÃO
BEGIN TRANSACTION

SELECT @@TRANCOUNT

UPDATE EMPREGADO_TEMP
SET SALARIO = SALARIO * 1.2
WHERE COD_DEPTO = 2

ROLLBACK TRANSACTION -- VOLTA A TRANSAÇÃO(DESFAZ O UPDATE)

SELECT * 
FROM EMPREGADO_TEMP
WHERE COD_DEPTO = 2

BEGIN TRANSACTION

UPDATE EMPREGADO_TEMP
SET SALARIO = SALARIO * 1.2
WHERE COD_DEPTO = 2

SELECT * 
FROM EMPREGADO_TEMP
WHERE COD_DEPTO = 2

ROLLBACK TRANSACTION -- VOLTA A TRANSAÇÃO(DESFAZ O UPDATE)

--CERTEZA DA EXECUÇÃO DO COMANDO ENTAO EFETIVAR O COMANDO
COMMIT TRANSACTION
