USE PEDIDOS

SELECT *
FROM TB_EMPREGADO
ORDER BY SALARIO

--IS NULL -> RETORNA SOMENTE OS REGISTROS EM QUE A COLUNA ESPECIFICADA TENHA NULABILIDADE (NULL)
--EXIBIR OS FUNCIONARIOS QUE POSSUEM SALARIO COM NULABILIDADE
SELECT CODFUN, NOME, SALARIO
FROM TB_EMPREGADO
WHERE SALARIO IS NULL

--IS NOT NULL
--NEGA A NULABILIDADE
SELECT CODFUN, NOME, SALARIO
FROM TB_EMPREGADO
WHERE SALARIO IS NOT NULL

--FUNÇAO ISNULL
--FAZER UMA QUERY PARA RETORNAR O CODFUN, NOME E SALARIO
--MAS NA COLUNA SALARIO QUE TEM NULL DEVE SER RETORNADO ZERO
/*
SINTAXE DA FUNÇÃO ISNULL
ISNULL(CHECAGEM_COLUNA, VALOR_A_GRAVAR)
*/
SELECT CODFUN, NOME, ISNULL (SALARIO,0) AS SALARIO
FROM TB_EMPREGADO
ORDER BY SALARIO 

--AUMENTAR O SALARIO EM 10%
SELECT CODFUN, NOME, SALARIO, ISNULL(SALARIO,0)*1.10 AS SALARIO_ATUAL
FROM TB_EMPREGADO
ORDER BY SALARIO 

SELECT NOME, ENDERECO, ISNULL(BAIRRO, 'NAO INFORMADO') AS BAIRRO 
FROM TB_CLIENTE
ORDER BY BAIRRO

--IIF
SELECT NOME, ENDERECO, IIF(BAIRRO='', 'NÃO INFORMADO', ISNULL(BAIRRO,'NÃO INFORMADO'))AS BAIRRO
FROM TB_CLIENTE
ORDER BY BAIRRO
