USE PEDIDOS

--VARIAVEL QUE RECEBERÁ O VALOR DE UMA QUERY
--CRIAR UM SCRIPT PARA RECEBER O CODFUN E O SCRIPT DEVE ARMAZENAR O SALARIO DO FUNCIONARIO EM UMA VARIAVEL E EXIBIR O CONTEUDO DA MESMA
DECLARE @CODIGO INT
		,@SALARIO NUMERIC (18,2)
SET @CODIGO = 5
SET @SALARIO = (
				SELECT SALARIO
				FROM TB_EMPREGADO
				WHERE CODFUN = @CODIGO)
PRINT CONCAT('SALARIO = ',@SALARIO)

--CRIAR UM SCRIPT PARA ARMAZENAR A QUANTIDADE DE REGISTROS DA TABELA DE FUNCIONARIOS
DECLARE @QTDE_REG INT
SET @QTDE_REG = (SELECT COUNT(*)
FROM TB_EMPREGADO)
SELECT @QTDE_REG AS QTDE_REGISTROS

