USE PEDIDOS

--INTRODUÇAO A PROGRAMAÇÃO
--CRIAR VARIAVEL (@)
--DECLARAR VARIAVEL PARAR ARMAZENAR UM NUMERO INTEIRO
DECLARE @VALOR INT
--ATRIBUIR O VALOR A VARIAVEL
SET @VALOR=10
--VISUALIZAR O CONTEUDO DA VARIAVEL
PRINT @VALOR
--OU
SELECT @VALOR AS VALOR

--REALIZAR CALCULOS COM VARIAVEIS
--SOMAR DOIS NUMEROS INTEIROS E EXIBIR O RESULTADO
DECLARE @NUM1 INT
		,@NUM2 INT
		,@SOMA INT
SET @NUM1=5
SET @NUM2=7
SET @SOMA= @NUM1+@NUM2
PRINT @SOMA

--CRIAR UM SCRITP PARA RECEBER O CODFUN E EXIBIR O NOME DO MESMO
DECLARE @CODFUN INT
SET @CODFUN=5
SELECT NOME
FROM TB_EMPREGADO
WHERE CODFUN = @CODFUN